// Decompiled with JetBrains decompiler
// Type: ZoomZoom.Models.Data.DataObject
// Assembly: ZoomZoom, Version=3.1.2.133, Culture=neutral, PublicKeyToken=null
// MVID: ABEAA923-4AD5-42AE-8951-938AC0FA3F1E
// Assembly location: \\storage-n01.thelaughingman.local\stuff\jaime_temp_DONT_dELETE\jnc8651\ZoomZoom.exe

using System;
using System.Collections.Generic;
using System.Data.SQLite;
using ZoomZoom.Models.Events;

namespace ZoomZoom.Models.Data
{
  public abstract class DataObject : CoreObject, IObjectChanged, IDatabaseObject
  {
    private Dictionary<string, object> dataDictionary;

    public abstract ObjectDataTable ZoomZoomTable { get; }

    public Dictionary<string, object> DataDictionary
    {
      get
      {
label_1:
        int num1 = 1033181537;
        Dictionary<string, object> dataDictionary;
        while (true)
        {
          int num2 = 1892704273;
          uint num3;
          bool flag;
          switch ((num3 = (uint) (num1 ^ num2)) % 7U)
          {
            case 0:
              num1 = (int) num3 * 445250154 ^ -303348187;
              continue;
            case 2:
              this.dataDictionary = this.GetDataDictionary();
              num1 = (int) num3 * 1626947235 ^ -491157099;
              continue;
            case 3:
              goto label_1;
            case 4:
              int num4 = !flag ? 154577491 : (num4 = 2051752750);
              int num5 = (int) num3 * 1569932016;
              num1 = num4 ^ num5;
              continue;
            case 5:
              dataDictionary = this.dataDictionary;
              num1 = 481882151;
              continue;
            case 6:
              flag = this.dataDictionary == null;
              num1 = (int) num3 * 847997990 ^ -1808420273;
              continue;
            default:
              goto label_8;
          }
        }
label_8:
        return dataDictionary;
      }
      set
      {
label_1:
        int num1 = 1076708490;
        while (true)
        {
          int num2 = 180940737;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              goto label_1;
            case 1:
              goto label_3;
            case 2:
              this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(3794575430U));
              num1 = (int) num3 * 1639439561 ^ 490538754;
              continue;
            case 3:
              this.dataDictionary = value;
              num1 = (int) num3 * -761990681 ^ 790955042;
              continue;
            default:
              goto label_6;
          }
        }
label_6:
        return;
label_3:;
      }
    }

    public abstract Dictionary<string, object> GetDataDictionary();

    public virtual bool SaveDatabaseObject()
    {
      bool flag1 = !this.IsDirty;
label_1:
      int num1 = 786613162;
      bool flag2;
      while (true)
      {
        int num2 = 572353263;
        uint num3;
        bool flag3;
        long data;
        int num4;
        switch ((num3 = (uint) (num1 ^ num2)) % 19U)
        {
          case 0:
            data = (long) this.DataDictionary[\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3466564611U)];
            num1 = (int) num3 * -1286168264 ^ 757267762;
            continue;
          case 1:
            int num5 = !flag3 ? -852481884 : (num5 = -1130291150);
            int num6 = (int) num3 * 321314170;
            num1 = num5 ^ num6;
            continue;
          case 2:
            num1 = (int) num3 * -23378575 ^ -23760089;
            continue;
          case 3:
            num1 = (int) num3 * 1918822514 ^ 491326301;
            continue;
          case 4:
            int num7 = !flag1 ? -558655012 : (num7 = -1793434130);
            int num8 = (int) num3 * -674471701;
            num1 = num7 ^ num8;
            continue;
          case 5:
            flag2 = true;
            num1 = (int) num3 * 983440418 ^ 80837734;
            continue;
          case 6:
            if (this.AutoGenerated)
            {
              num4 = 0;
              break;
            }
            num1 = 2058045592;
            continue;
          case 7:
            num1 = 1038902329;
            continue;
          case 8:
            this.Uri = data;
            num1 = (int) num3 * -50015664 ^ 1459097669;
            continue;
          case 9:
            num1 = (int) num3 * 1386991380 ^ -443906843;
            continue;
          case 10:
            num1 = (int) num3 * -1991307459 ^ 797546915;
            continue;
          case 12:
            flag2 = true;
            num1 = (int) num3 * 301040842 ^ -622154311;
            continue;
          case 13:
            num4 = this.Engine.ZoomZoomDatabase.SaveObject(this.ZoomZoomTable, this.DataDictionary) ? 1 : 0;
            break;
          case 14:
            flag2 = false;
            num1 = (int) num3 * -1019351850 ^ 420914381;
            continue;
          case 15:
            goto label_1;
          case 16:
            int num9 = this.Uri != data ? -1391168910 : (num9 = -1276146453);
            int num10 = (int) num3 * 2025319370;
            num1 = num9 ^ num10;
            continue;
          case 17:
            this.isDirty = false;
            num1 = 1695849776;
            continue;
          case 18:
            num1 = (int) num3 * 585858395 ^ -1240038154;
            continue;
          default:
            goto label_23;
        }
        flag3 = num4 != 0;
        num1 = 188257030;
      }
label_23:
      return flag2;
    }

    public virtual bool DeleteDatabaseObject()
    {
label_1:
      int num1 = -457706168;
      bool flag;
      while (true)
      {
        int num2 = -32414463;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 0:
            goto label_1;
          case 1:
            flag = this.Engine.ZoomZoomDatabase.DeleteObject(this.ZoomZoomTable, this.DataDictionary);
            num1 = (int) num3 * -903331288 ^ -1902076875;
            continue;
          default:
            goto label_4;
        }
      }
label_4:
      return flag;
    }

    public abstract bool LoadDataObject(SQLiteDataReader cReader);

    public virtual ObjectDataTable GetTableName()
    {
      return ObjectDataTable.Unkonown;
    }

    object IDatabaseObject.LoadDatabaseObject(SQLiteDataReader cReader)
    {
label_1:
      int num1 = -607765157;
      object obj;
      while (true)
      {
        int num2 = -503072694;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 1:
            obj = (object) this.LoadDataObject(cReader);
            num1 = (int) num3 * -725604623 ^ 1614957185;
            continue;
          case 2:
            num1 = (int) num3 * -271900285 ^ 862176780;
            continue;
          case 3:
            goto label_1;
          default:
            goto label_5;
        }
      }
label_5:
      return obj;
    }

    public void Publish(ObjectChangedEventPayload payload)
    {
      throw DataObject.\u206D‫‍‏‮‏‬‍‭‭​‍​​⁬​‍‌⁬⁬‏‌‮‮‫‭‍⁮⁮⁪‌‎⁬⁮⁪‭‏⁪‭‮‮();
    }

    static NotImplementedException \u206D‫‍‏‮‏‬‍‭‭​‍​​⁬​‍‌⁬⁬‏‌‮‮‫‭‍⁮⁮⁪‌‎⁬⁮⁪‭‏⁪‭‮‮()
    {
      return new NotImplementedException();
    }
  }
}
