// Decompiled with JetBrains decompiler
// Type: ZoomZoom.Models.Chats.MessageCategory
// Assembly: ZoomZoom, Version=3.1.2.133, Culture=neutral, PublicKeyToken=null
// MVID: ABEAA923-4AD5-42AE-8951-938AC0FA3F1E
// Assembly location: \\storage-n01.thelaughingman.local\stuff\jaime_temp_DONT_dELETE\jnc8651\ZoomZoom.exe

using log4net;
using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Runtime.InteropServices;
using ZoomZoom.Models.Data;

namespace ZoomZoom.Models.Chats
{
  public class MessageCategory : DataObject
  {
    private string categoryName = string.Empty;
    private DateTime dateCreated = DateTime.MinValue;
    private DateTime dateModified = DateTime.MinValue;
    private bool autogenerated = false;

    public override TraceType TraceType
    {
      get
      {
label_1:
        int num1 = 1730491579;
        TraceType traceType;
        while (true)
        {
          int num2 = 1348198896;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              traceType = TraceType.Chat;
              num1 = (int) num3 * 1953646634 ^ -94533909;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return traceType;
      }
    }

    public DateTime DateCreated
    {
      get
      {
        return this.dateCreated;
      }
      internal set
      {
label_1:
        int num1 = -117198225;
        while (true)
        {
          int num2 = -1262593665;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              this.dateCreated = value;
              this.RaisePropertyChanged(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(1164059611U));
              num1 = -1327133399;
              continue;
            case 1:
              num1 = (int) num3 * -2131979422 ^ 1507486541;
              continue;
            case 2:
              int num4 = this.dateCreated == value ? -141674675 : (num4 = -413971435);
              int num5 = (int) num3 * -609897138;
              num1 = num4 ^ num5;
              continue;
            case 3:
              goto label_3;
            case 4:
              goto label_1;
            default:
              goto label_7;
          }
        }
label_7:
        return;
label_3:;
      }
    }

    public DateTime DateModified
    {
      get
      {
label_1:
        int num1 = 1959114162;
        DateTime dateModified;
        while (true)
        {
          int num2 = 730854307;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              dateModified = this.dateModified;
              num1 = (int) num3 * 573550659 ^ 492743113;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return dateModified;
      }
      internal set
      {
        if (!(this.dateModified == value))
          goto label_5;
label_1:
        int num1 = -788305447;
label_2:
        while (true)
        {
          int num2 = -1365102193;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              goto label_1;
            case 1:
              this.RaisePropertyChanged(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(2430253183U));
              num1 = (int) num3 * -531401516 ^ -2123913640;
              continue;
            case 2:
              num1 = (int) num3 * 1601625314 ^ 941596340;
              continue;
            case 3:
              goto label_5;
            case 4:
              goto label_3;
            default:
              goto label_7;
          }
        }
label_7:
        return;
label_3:
        return;
label_5:
        this.dateModified = value;
        num1 = -1818230193;
        goto label_2;
      }
    }

    public string CategoryName
    {
      get
      {
label_1:
        int num1 = 1651838539;
        string categoryName;
        while (true)
        {
          int num2 = 1858364506;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 1:
              categoryName = this.categoryName;
              num1 = (int) num3 * -1879004600 ^ -1635002311;
              continue;
            case 2:
              goto label_1;
            case 3:
              num1 = (int) num3 * 128979610 ^ -2045453904;
              continue;
            default:
              goto label_5;
          }
        }
label_5:
        return categoryName;
      }
      set
      {
label_1:
        int num1 = -807100459;
        while (true)
        {
          int num2 = -1518981560;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 6U)
          {
            case 0:
              this.categoryName = value;
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(1149670357U));
              num1 = -163530079;
              continue;
            case 1:
              int num4 = MessageCategory.\u200D‏‪​⁭⁭‬‮‭‪‮⁬⁬⁮‮‎‎⁭⁪​‬‎‌‬‍⁯⁭‪⁭‪‪‫⁯‎‬‎⁮⁬⁯‭‮(this.categoryName, value) ? 2141706990 : (num4 = 57023077);
              int num5 = (int) num3 * -44252111;
              num1 = num4 ^ num5;
              continue;
            case 2:
              goto label_1;
            case 3:
              num1 = (int) num3 * 1599478591 ^ 604309879;
              continue;
            case 4:
              goto label_3;
            case 5:
              num1 = (int) num3 * -2041863605 ^ 2067543841;
              continue;
            default:
              goto label_8;
          }
        }
label_8:
        return;
label_3:;
      }
    }

    public override ObjectDataTable ZoomZoomTable
    {
      get
      {
label_1:
        int num1 = -1729593237;
        ObjectDataTable objectDataTable;
        while (true)
        {
          int num2 = -1108121951;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              objectDataTable = ObjectDataTable.MessageCategory;
              num1 = (int) num3 * 1943142389 ^ -259333226;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return objectDataTable;
      }
    }

    private MessageCategory()
    {
    }

    public MessageCategory(string categoryName)
    {
label_1:
      int num1 = 1394916688;
      while (true)
      {
        int num2 = 416149483;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 6U)
        {
          case 0:
            this.categoryName = categoryName;
            num1 = (int) num3 * -155080097 ^ -153481236;
            continue;
          case 1:
            num1 = (int) num3 * -298721264 ^ -1652859649;
            continue;
          case 2:
            goto label_3;
          case 3:
            this.dateCreated = DateTime.Now;
            num1 = (int) num3 * -916429339 ^ 2045451415;
            continue;
          case 4:
            goto label_1;
          case 5:
            this.dateModified = DateTime.Now;
            num1 = (int) num3 * -987586563 ^ 1412038554;
            continue;
          default:
            goto label_8;
        }
      }
label_8:
      return;
label_3:;
    }

    public static MessageCategory Load(SQLiteDataReader cReader)
    {
      MessageCategory messageCategory1 = new MessageCategory();
      bool flag = messageCategory1.LoadDataObject(cReader);
label_1:
      int num1 = 2053261143;
      MessageCategory messageCategory2;
      while (true)
      {
        int num2 = 669444573;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 7U)
        {
          case 0:
            goto label_1;
          case 1:
            int num4 = flag ? -1464089883 : (num4 = -822879486);
            int num5 = (int) num3 * 1751563925;
            num1 = num4 ^ num5;
            continue;
          case 2:
            messageCategory2 = messageCategory1;
            num1 = (int) num3 * -1768348315 ^ -512837214;
            continue;
          case 3:
            num1 = (int) num3 * -1200683460 ^ -1981816956;
            continue;
          case 5:
            num1 = 409858471;
            continue;
          case 6:
            messageCategory2 = (MessageCategory) null;
            num1 = (int) num3 * 1703738034 ^ -2049952006;
            continue;
          default:
            goto label_8;
        }
      }
label_8:
      return messageCategory2;
    }

    public override bool Equals(object obj)
    {
label_1:
      int num1 = -370987318;
      bool flag;
      while (true)
      {
        int num2 = -448761122;
        uint num3;
        MessageCategory messageCategory;
        int num4;
        switch ((num3 = (uint) (num1 ^ num2)) % 9U)
        {
          case 0:
            goto label_1;
          case 1:
            flag = this.\u206D‌‬‏‌‫⁯​‮⁭‏⁫‎‬‬‏‌⁬‎​‮‪‭‎⁮​‏‭‎​⁯‫‮‌‪‍‪‫‍‏‮(obj);
            num1 = -1067506401;
            continue;
          case 2:
            messageCategory = obj as MessageCategory;
            num1 = (int) num3 * 744045036 ^ -1281504650;
            continue;
          case 3:
            num1 = (int) num3 * -2002971952 ^ 280482994;
            continue;
          case 4:
            if (!MessageCategory.\u202E⁮‮‍‏⁪⁪⁬‫⁮‫‍‫‏‏⁯‍‮‬⁯‫⁫‮⁮⁪⁯⁭‭⁬‬‏⁯⁪‌⁭‭‏⁪‌⁮‮(messageCategory.CategoryName))
            {
              num1 = (int) num3 * 1106339154 ^ 1538771794;
              continue;
            }
            break;
          case 5:
            num4 = !MessageCategory.\u202E⁮‮‍‏⁪⁪⁬‫⁮‫‍‫‏‏⁯‍‮‬⁯‫⁫‮⁮⁪⁯⁭‭⁬‬‏⁯⁪‌⁭‭‏⁪‌⁮‮(this.CategoryName) ? 1 : 0;
            goto label_10;
          case 6:
            flag = MessageCategory.\u206B‍‭‌‏‌‮⁯‭‫​⁭⁯‬⁯⁯​‪⁪⁭‎⁯‭‮⁮⁫‫⁬⁯‭⁫‪‫​⁮‬⁫​‏‬‮(messageCategory.CategoryName, this.CategoryName);
            num1 = (int) num3 * -1822781958 ^ -1994457608;
            continue;
          case 7:
            if (messageCategory != null)
            {
              num1 = (int) num3 * 519940722 ^ -294052001;
              continue;
            }
            break;
          default:
            goto label_14;
        }
        num4 = 0;
label_10:
        int num5;
        num1 = num5 = num4 != 0 ? -1514398769 : (num5 = -1249523412);
      }
label_14:
      return flag;
    }

    public override int GetHashCode()
    {
      if (MessageCategory.\u202E⁮‮‍‏⁪⁪⁬‫⁮‫‍‫‏‏⁯‍‮‬⁯‫⁫‮⁮⁪⁯⁭‭⁬‬‏⁯⁪‌⁭‭‏⁪‌⁮‮(this.CategoryName))
        goto label_4;
label_1:
      int num1 = 463455675;
label_2:
      int num2;
      while (true)
      {
        int num3 = 1058992422;
        uint num4;
        switch ((num4 = (uint) (num1 ^ num3)) % 6U)
        {
          case 0:
            goto label_1;
          case 1:
            goto label_4;
          case 2:
            num1 = (int) num4 * 2057308564 ^ -1947940234;
            continue;
          case 3:
            num2 = MessageCategory.\u202B‍⁫‭‏‎⁯⁮‫‪‍‌‌‮‍‪⁪‭‪‪⁮‌‪‍⁯⁬⁭⁭⁫‮​‬‌⁯⁯‍‪‎⁮‮((object) this.CategoryName);
            num1 = (int) num4 * -2058926595 ^ -462900993;
            continue;
          case 5:
            num1 = (int) num4 * -2135287563 ^ -495982966;
            continue;
          default:
            goto label_7;
        }
      }
label_7:
      return num2;
label_4:
      num2 = this.\u202E‏⁮‭‏‌⁮⁬⁪⁬‪​‎‎⁯⁮‎‌⁯⁮‫​⁭‏‎⁫⁭‮‮‫‪‪‎⁯‏‭‬‭​⁬‮();
      num1 = 1359121178;
      goto label_2;
    }

    internal List<MessageContent> GetMessageContents()
    {
      return this.Engine.GetMessageContents(this);
    }

    public override Dictionary<string, object> GetDataDictionary()
    {
      Dictionary<string, object> dictionary1 = new Dictionary<string, object>();
label_1:
      int num1 = 727095005;
      Dictionary<string, object> dictionary2;
      while (true)
      {
        int num2 = 362762166;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 11U)
        {
          case 0:
            goto label_1;
          case 1:
            dictionary2 = dictionary1;
            num1 = (int) num3 * 1067463459 ^ 544908105;
            continue;
          case 3:
            dictionary1.Add(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(3382247043U), (object) this.CategoryName);
            num1 = (int) num3 * 497864733 ^ -1459772990;
            continue;
          case 4:
            num1 = (int) num3 * -732395388 ^ -370247243;
            continue;
          case 5:
            dictionary1.Add(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(1679528045U), (object) this.DateCreated);
            num1 = (int) num3 * 1439730095 ^ -845714317;
            continue;
          case 6:
            dictionary1.Add(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(1809658423U), (object) this.Uri);
            num1 = (int) num3 * -368317543 ^ -1329384139;
            continue;
          case 7:
            num1 = (int) num3 * 974524689 ^ -119000417;
            continue;
          case 8:
            dictionary1.Add(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(3397799221U), (object) this.DateModified);
            num1 = (int) num3 * -1653265608 ^ 364691003;
            continue;
          case 9:
            num1 = (int) num3 * 1852868613 ^ -1640723564;
            continue;
          case 10:
            num1 = (int) num3 * 405063700 ^ 1721239240;
            continue;
          default:
            goto label_12;
        }
      }
label_12:
      return dictionary2;
    }

    public override bool LoadDataObject(SQLiteDataReader cReader)
    {
      bool flag1 = false;
      try
      {
label_2:
        int num1 = 592644964;
        while (true)
        {
          int num2 = 439548641;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 6U)
          {
            case 1:
              num1 = (int) num3 * -372402885 ^ -901739676;
              continue;
            case 2:
              this.dateCreated = cReader.GetFieldValueDateTime(\u003CModule\u003E.\u200E‏⁯‍‬⁭⁪‌‌‌⁪⁫‫‎⁫‮⁬‎‌⁮⁪⁪⁭‍‌⁫‮‬‎⁬‎‌‎‌⁪‫‬‮⁮‮<string>(2182723723U));
              num1 = (int) num3 * 1785519124 ^ -1170044113;
              continue;
            case 3:
              this.uri = cReader.GetFieldValueLong(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3466564611U));
              this.categoryName = cReader.GetFieldValueString(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(1813587343U));
              num1 = (int) num3 * -2010890158 ^ 210159811;
              continue;
            case 4:
              this.dateModified = cReader.GetFieldValueDateTime(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(3335598589U));
              flag1 = true;
              num1 = (int) num3 * -1539431468 ^ 1732057398;
              continue;
            case 5:
              goto label_2;
            default:
              goto label_13;
          }
        }
      }
      catch (Exception ex)
      {
label_9:
        int num1 = 1916358262;
        while (true)
        {
          int num2 = 439548641;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              goto label_9;
            case 2:
              MessageCategory.\u200C‍‏‏‎‎‏⁭‏‪‌⁮‮‏⁬‌⁯⁭‫⁬⁮‬⁯‍‍‮​⁫⁪⁮⁮⁭​​⁬⁪‮‭⁫⁪‮(CoreObject.log, (object) ex);
              num1 = (int) num3 * 240466506 ^ -855794604;
              continue;
            case 3:
              num1 = (int) num3 * 1292990377 ^ -464429552;
              continue;
            default:
              goto label_13;
          }
        }
      }
label_13:
      bool flag2 = flag1;
label_14:
      int num4 = 2009906581;
      while (true)
      {
        int num1 = 439548641;
        uint num2;
        switch ((num2 = (uint) (num4 ^ num1)) % 3U)
        {
          case 0:
            goto label_14;
          case 1:
            num4 = (int) num2 * -1391612985 ^ 467925324;
            continue;
          default:
            goto label_17;
        }
      }
label_17:
      return flag2;
    }

    static bool \u200D‏‪​⁭⁭‬‮‭‪‮⁬⁬⁮‮‎‎⁭⁪​‬‎‌‬‍⁯⁭‪⁭‪‪‫⁯‎‬‎⁮⁬⁯‭‮([In] string obj0, [In] string obj1)
    {
      return obj0 == obj1;
    }

    static bool \u202E⁮‮‍‏⁪⁪⁬‫⁮‫‍‫‏‏⁯‍‮‬⁯‫⁫‮⁮⁪⁯⁭‭⁬‬‏⁯⁪‌⁭‭‏⁪‌⁮‮([In] string obj0)
    {
      return string.IsNullOrEmpty(obj0);
    }

    static bool \u206B‍‭‌‏‌‮⁯‭‫​⁭⁯‬⁯⁯​‪⁪⁭‎⁯‭‮⁮⁫‫⁬⁯‭⁫‪‫​⁮‬⁫​‏‬‮([In] string obj0, [In] string obj1)
    {
      return obj0.Equals(obj1);
    }

    bool \u206D‌‬‏‌‫⁯​‮⁭‏⁫‎‬‬‏‌⁬‎​‮‪‭‎⁮​‏‭‎​⁯‫‮‌‪‍‪‫‍‏‮([In] object obj0)
    {
      return base.Equals(obj0);
    }

    static int \u202B‍⁫‭‏‎⁯⁮‫‪‍‌‌‮‍‪⁪‭‪‪⁮‌‪‍⁯⁬⁭⁭⁫‮​‬‌⁯⁯‍‪‎⁮‮([In] object obj0)
    {
      return obj0.GetHashCode();
    }

    int \u202E‏⁮‭‏‌⁮⁬⁪⁬‪​‎‎⁯⁮‎‌⁯⁮‫​⁭‏‎⁫⁭‮‮‫‪‪‎⁯‏‭‬‭​⁬‮()
    {
      return base.GetHashCode();
    }

    static void \u200C‍‏‏‎‎‏⁭‏‪‌⁮‮‏⁬‌⁯⁭‫⁬⁮‬⁯‍‍‮​⁫⁪⁮⁮⁭​​⁬⁪‮‭⁫⁪‮([In] ILog obj0, [In] object obj1)
    {
      obj0.Error(obj1);
    }
  }
}
