// Decompiled with JetBrains decompiler
// Type: ZoomZoom.ChatManager
// Assembly: ZoomZoom, Version=3.1.2.133, Culture=neutral, PublicKeyToken=null
// MVID: ABEAA923-4AD5-42AE-8951-938AC0FA3F1E
// Assembly location: \\storage-n01.thelaughingman.local\stuff\jaime_temp_DONT_dELETE\jnc8651\ZoomZoom.exe

using log4net;
using Microsoft.Practices.Prism.Events;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using ZoomZoom.Chats;
using ZoomZoom.Common;
using ZoomZoom.Models.Activities;
using ZoomZoom.Models.Chats;

namespace ZoomZoom
{
  public class ChatManager : ManagerBase
  {
    private static ChatManager instance = (ChatManager) null;
    private DateTime videoChatLinkLastCompleted = DateTime.MinValue;
    private List<string> notifiedUserNames = new List<string>();
    private Dictionary<string, ActivityBase> heldActivities = new Dictionary<string, ActivityBase>();
    private List<string> autoGeneratedMessages = new List<string>();
    protected new readonly IEventAggregator _eventAggregator;
    private static readonly object chatLocker;
    private static SortedDictionary<int, DateTime> pendingVideoLinks;
    private static Dictionary<IntPtr, VideoChatLink> activeVideoChatLinks;
    private static List<ChatLinkObject> pendingLinkObjects;

    public static SortedDictionary<int, DateTime> PendingVideoLinks
    {
      get
      {
label_1:
        int num1 = -1094652791;
        SortedDictionary<int, DateTime> pendingVideoLinks;
        while (true)
        {
          int num2 = -829641958;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              pendingVideoLinks = ChatManager.pendingVideoLinks;
              num1 = (int) num3 * 1513213224 ^ -1020852933;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return pendingVideoLinks;
      }
      set
      {
        ChatManager.pendingVideoLinks = value;
      }
    }

    public static Dictionary<IntPtr, VideoChatLink> ActiveVideoChatLinks
    {
      get
      {
label_1:
        int num1 = 110670848;
        Dictionary<IntPtr, VideoChatLink> activeVideoChatLinks;
        while (true)
        {
          int num2 = 851013380;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 2:
              activeVideoChatLinks = ChatManager.activeVideoChatLinks;
              num1 = (int) num3 * 1146489751 ^ -2135034661;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return activeVideoChatLinks;
      }
      set
      {
        ChatManager.activeVideoChatLinks = value;
      }
    }

    public DateTime VideoChatLinkLastCompleted
    {
      get
      {
        DateTime linkLastCompleted = this.videoChatLinkLastCompleted;
label_1:
        int num1 = 2092444530;
        while (true)
        {
          int num2 = 1185885909;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * 268389135 ^ -1723671452;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return linkLastCompleted;
      }
      private set
      {
        this.videoChatLinkLastCompleted = value;
      }
    }

    public Dictionary<string, ActivityBase> HeldActivities
    {
      get
      {
label_1:
        int num1 = 1570799289;
        Dictionary<string, ActivityBase> heldActivities;
        while (true)
        {
          int num2 = 336531617;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              heldActivities = this.heldActivities;
              num1 = (int) num3 * 178051796 ^ 1985023987;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return heldActivities;
      }
      set
      {
label_1:
        int num1 = 1066267526;
        while (true)
        {
          int num2 = 1720572964;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_3;
            case 1:
              this.heldActivities = value;
              num1 = (int) num3 * 814626888 ^ -226809778;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_5;
          }
        }
label_5:
        return;
label_3:;
      }
    }

    public static List<ChatLinkObject> PendingLinkObjects
    {
      get
      {
        List<ChatLinkObject> pendingLinkObjects = ChatManager.pendingLinkObjects;
label_1:
        int num1 = -1381603174;
        while (true)
        {
          int num2 = -110192217;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * -1516642168 ^ -719722621;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return pendingLinkObjects;
      }
      set
      {
label_1:
        int num1 = 1956328783;
        while (true)
        {
          int num2 = 1542375712;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              goto label_3;
            case 2:
              ChatManager.pendingLinkObjects = value;
              num1 = (int) num3 * -819986515 ^ -1040326641;
              continue;
            default:
              goto label_5;
          }
        }
label_5:
        return;
label_3:;
      }
    }

    public static ChatManager Instance
    {
      get
      {
        bool flag1 = ChatManager.instance == null;
label_1:
        int num1 = 883152201;
        while (true)
        {
          int num2 = 1880296504;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              num1 = (int) num3 * 1781745129 ^ -771705986;
              continue;
            case 1:
              if (flag1)
              {
                num1 = (int) num3 * -1240036351 ^ 849646201;
                continue;
              }
              goto label_23;
            case 3:
              goto label_1;
            default:
              goto label_6;
          }
        }
label_6:
        object chatLocker = ChatManager.chatLocker;
        bool flag2 = false;
        try
        {
          ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(chatLocker, ref flag2);
label_8:
          int num2 = 661507621;
          while (true)
          {
            int num3 = 1880296504;
            uint num4;
            bool flag3;
            switch ((num4 = (uint) (num2 ^ num3)) % 7U)
            {
              case 0:
                goto label_8;
              case 1:
                ChatManager.instance = new ChatManager();
                num2 = (int) num4 * 2018654990 ^ -1301801339;
                continue;
              case 2:
                num2 = (int) num4 * 877242488 ^ 1293333975;
                continue;
              case 3:
                flag3 = ChatManager.instance == null;
                num2 = (int) num4 * 1562855763 ^ -659913791;
                continue;
              case 4:
                int num5 = !flag3 ? 880451567 : (num5 = 1747941055);
                int num6 = (int) num4 * -866788709;
                num2 = num5 ^ num6;
                continue;
              case 6:
                num2 = (int) num4 * -2004698222 ^ 1330709419;
                continue;
              default:
                goto label_20;
            }
          }
        }
        finally
        {
          if (flag2)
          {
label_16:
            int num2 = 511931638;
            while (true)
            {
              int num3 = 1880296504;
              uint num4;
              switch ((num4 = (uint) (num2 ^ num3)) % 3U)
              {
                case 1:
                  ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(chatLocker);
                  num2 = (int) num4 * 894619873 ^ -822810215;
                  continue;
                case 2:
                  goto label_16;
                default:
                  goto label_19;
              }
            }
          }
label_19:;
        }
label_20:
label_21:
        int num7 = 1874490762;
label_22:
        while (true)
        {
          int num2 = 1880296504;
          uint num3;
          switch ((num3 = (uint) (num7 ^ num2)) % 4U)
          {
            case 1:
              num7 = (int) num3 * -2058900789 ^ 232975731;
              continue;
            case 2:
              goto label_23;
            case 3:
              goto label_21;
            default:
              goto label_25;
          }
        }
label_25:
        ChatManager instance;
        return instance;
label_23:
        instance = ChatManager.instance;
        num7 = 543907185;
        goto label_22;
      }
    }

    public override TraceType TraceType
    {
      get
      {
label_1:
        int num1 = 803650623;
        TraceType traceType;
        while (true)
        {
          int num2 = 1796451882;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              traceType = TraceType.Chat;
              num1 = (int) num3 * -310669393 ^ 580873466;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return traceType;
      }
    }

    public List<string> AutoGeneratedMessages
    {
      get
      {
label_1:
        int num1 = -105594299;
        List<string> generatedMessages;
        while (true)
        {
          int num2 = -1492812329;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 2:
              generatedMessages = this.autoGeneratedMessages;
              num1 = (int) num3 * -457246580 ^ -1809965171;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return generatedMessages;
      }
      set
      {
        this.autoGeneratedMessages = value;
      }
    }

    static ChatManager()
    {
label_1:
      int num1 = 645175365;
      while (true)
      {
        int num2 = 1953304845;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 0:
            goto label_1;
          case 1:
            ChatManager.chatLocker = ChatManager.\u200D⁯​‏‭‪‌⁮⁯‬‍⁬⁯⁮‎⁭​⁮​⁯⁮‌⁫⁪⁪⁮⁯‏‏⁮‬​‭⁬‭⁭‭‬‌‫‮();
            ChatManager.pendingVideoLinks = new SortedDictionary<int, DateTime>();
            num1 = (int) num3 * 894889192 ^ -395927932;
            continue;
          default:
            goto label_4;
        }
      }
label_4:
      ChatManager.activeVideoChatLinks = new Dictionary<IntPtr, VideoChatLink>();
      ChatManager.pendingLinkObjects = new List<ChatLinkObject>();
    }

    private ChatManager()
    {
label_1:
      int num1 = -567832321;
      while (true)
      {
        int num2 = -1030860465;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 6U)
        {
          case 0:
            goto label_1;
          case 1:
            this._eventAggregator = ApplicationService.Instance.EventAggregator;
            num1 = (int) num3 * -986426739 ^ -918216394;
            continue;
          case 2:
            num1 = (int) num3 * 423627927 ^ -915113336;
            continue;
          case 3:
            num1 = (int) num3 * -1290780091 ^ 1838515555;
            continue;
          case 4:
            ((CompositePresentationEvent<ChatLinkObject>) this._eventAggregator.GetEvent<ChatLinkEvent>()).Subscribe(new Action<ChatLinkObject>(this.AddChatLinkEvent), (ThreadOption) 2);
            num1 = (int) num3 * 697990156 ^ -473155074;
            continue;
          default:
            goto label_7;
        }
      }
label_7:
      ((CompositePresentationEvent<ZoomChat>) this._eventAggregator.GetEvent<ChatAutoGenerated>()).Subscribe(new Action<ZoomChat>(this.AddAutoGeneratedMessage), (ThreadOption) 2, true);
    }

    internal override void Cancel()
    {
label_1:
      int num1 = -227257780;
      object managerLock;
      while (true)
      {
        int num2 = -1131972636;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 1:
            managerLock = ManagerBase.managerLock;
            num1 = (int) num3 * -1421755956 ^ -506802795;
            continue;
          case 2:
            goto label_1;
          default:
            goto label_4;
        }
      }
label_4:
      bool flag = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(managerLock, ref flag);
label_6:
        int num2 = -272824211;
        while (true)
        {
          int num3 = -1131972636;
          uint num4;
          switch ((num4 = (uint) (num2 ^ num3)) % 6U)
          {
            case 0:
              num2 = (int) num4 * 554297070 ^ 878883141;
              continue;
            case 1:
              goto label_16;
            case 2:
              this.CancelRequested = true;
              num2 = (int) num4 * -436720525 ^ -1924923716;
              continue;
            case 3:
              num2 = (int) num4 * -1545213360 ^ 276786447;
              continue;
            case 4:
              goto label_6;
            case 5:
              num2 = (int) num4 * -1212483312 ^ -790334708;
              continue;
            default:
              goto label_12;
          }
        }
label_12:
        return;
label_16:;
      }
      finally
      {
        if (flag)
        {
label_14:
          int num2 = -1190515339;
          while (true)
          {
            int num3 = -1131972636;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 4U)
            {
              case 0:
                goto label_14;
              case 1:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(managerLock);
                num2 = (int) num4 * -1114148214 ^ -1658256851;
                continue;
              case 3:
                num2 = (int) num4 * 2099564735 ^ 1631774259;
                continue;
              default:
                goto label_19;
            }
          }
        }
label_19:;
      }
    }

    [STAThread]
    internal Task ManageChatsAsync(CancellationToken token)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      ChatManager.\u003CManageChatsAsync\u003Ed__29 manageChatsAsyncD29 = new ChatManager.\u003CManageChatsAsync\u003Ed__29();
label_1:
      int num1 = -528016668;
      while (true)
      {
        int num2 = -1093616413;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 0:
            goto label_1;
          case 2:
            // ISSUE: reference to a compiler-generated field
            manageChatsAsyncD29.\u003C\u003Et__builder = AsyncTaskMethodBuilder.Create();
            // ISSUE: reference to a compiler-generated field
            manageChatsAsyncD29.\u003C\u003E1__state = -1;
            // ISSUE: reference to a compiler-generated field
            AsyncTaskMethodBuilder tBuilder = manageChatsAsyncD29.\u003C\u003Et__builder;
            // ISSUE: explicit reference operation
            // ISSUE: explicit reference operation
            // ISSUE: cast to a reference type
            ((AsyncTaskMethodBuilder) @tBuilder).Start<ChatManager.\u003CManageChatsAsync\u003Ed__29>((M0&) @manageChatsAsyncD29);
            num1 = (int) num3 * -1894347450 ^ -84298086;
            continue;
          case 3:
            // ISSUE: reference to a compiler-generated field
            manageChatsAsyncD29.\u003C\u003E4__this = this;
            // ISSUE: reference to a compiler-generated field
            manageChatsAsyncD29.token = token;
            num1 = (int) num3 * -384076713 ^ 69368716;
            continue;
          default:
            goto label_5;
        }
      }
label_5:
      // ISSUE: reference to a compiler-generated field
      // ISSUE: explicit reference operation
      return ((AsyncTaskMethodBuilder) @manageChatsAsyncD29.\u003C\u003Et__builder).get_Task();
    }

    [STAThread]
    public bool ManageChats(CancellationToken token)
    {
label_1:
      int num1 = -855814083;
      bool flag1;
      while (true)
      {
        int num2 = -1605504178;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 9U)
        {
          case 0:
            this.SharedData = this.Engine.SharedData;
            num1 = (int) num3 * 1861273341 ^ -2102574457;
            continue;
          case 1:
            this.Token = token;
            num1 = (int) num3 * 366813469 ^ 2090327324;
            continue;
          case 2:
            num1 = (int) num3 * 1458414881 ^ -435309816;
            continue;
          case 3:
            goto label_27;
          case 4:
            goto label_1;
          case 6:
            num1 = (int) num3 * 1093534246 ^ -1635610340;
            continue;
          case 7:
            flag1 = false;
            this.Initialize();
            num1 = (int) num3 * -433988854 ^ 1840214639;
            continue;
          case 8:
            num1 = (int) num3 * 1180672513 ^ -1506965843;
            continue;
          default:
            goto label_9;
        }
      }
label_9:
      try
      {
label_11:
        int num2 = -348311273;
        while (true)
        {
          int num3 = -1605504178;
          uint num4;
          bool initialized;
          switch ((num4 = (uint) (num2 ^ num3)) % 12U)
          {
            case 1:
              num2 = -854497258;
              continue;
            case 2:
              goto label_11;
            case 3:
              this.ManageVideoChatLinks();
              num2 = (int) num4 * 310862313 ^ -1094196708;
              continue;
            case 4:
              num2 = -2006224451;
              continue;
            case 5:
              initialized = this.Engine.HookManager.Initialized;
              num2 = (int) num4 * -534919524 ^ -2091867144;
              continue;
            case 6:
              int num5 = !initialized ? -2119507364 : (num5 = -1450135821);
              int num6 = (int) num4 * -252610955;
              num2 = num5 ^ num6;
              continue;
            case 7:
              ChatManager.\u200F⁬‏‎‏⁯⁬‭⁬‮‎⁮‪⁯‬⁫⁬‬‏‍⁭⁬‬​⁫⁪⁬‮‏‫⁯‫‌⁯⁬‫‮‎⁫‮‮(50);
              num2 = (int) num4 * -982757976 ^ -1838003588;
              continue;
            case 8:
              num2 = (int) num4 * 1562407691 ^ -1746686913;
              continue;
            case 9:
              ChatManager.\u200F⁬‏‎‏⁯⁬‭⁬‮‎⁮‪⁯‬⁫⁬‬‏‍⁭⁬‬​⁫⁪⁬‮‏‫⁯‫‌⁯⁬‫‮‎⁫‮‮(50);
              num2 = (int) num4 * -2145259037 ^ 2132417925;
              continue;
            case 10:
              num2 = (int) num4 * -913272260 ^ -1974722981;
              continue;
            case 11:
              this.ImportZoomChatDB();
              num2 = (int) num4 * 1227837539 ^ 868860460;
              continue;
            default:
              goto label_24;
          }
        }
      }
      catch (Exception ex)
      {
        ChatManager.\u202B‏‮‬‬‪⁮⁯‎⁯⁪‌⁫‫⁪‪‏⁭‬‭⁬⁬​⁪‬⁫⁪‪‬⁮‭⁬⁭‬‎‭⁪⁭‎⁬‮(CoreObject.log, (object) ex);
      }
label_24:
label_25:
      int num7 = -646038235;
label_26:
      bool flag2;
      bool flag3;
      while (true)
      {
        int num2 = -1605504178;
        uint num3;
        switch ((num3 = (uint) (num7 ^ num2)) % 7U)
        {
          case 0:
            if (!this.CancelRequested)
            {
              num7 = (int) num3 * 1915931694 ^ -1037027731;
              continue;
            }
            goto label_30;
          case 2:
            goto label_29;
          case 3:
            goto label_25;
          case 4:
            if (!flag2)
            {
              num7 = (int) num3 * 695757952 ^ 833603576;
              continue;
            }
            goto label_9;
          case 5:
            flag3 = !flag1;
            num7 = (int) num3 * 805542168 ^ 1768493615;
            continue;
          case 6:
            goto label_27;
          default:
            goto label_37;
        }
      }
label_29:
      int num8 = this.Engine.SharedData != null ? 1 : 0;
      goto label_31;
label_37:
      return flag3;
label_27:
      if (!flag1)
      {
        num7 = -1402749965;
        goto label_26;
      }
label_30:
      num8 = 0;
label_31:
      flag2 = num8 != 0;
      num7 = -607803213;
      goto label_26;
    }

    internal bool ImportZoomChatDB()
    {
      bool flag1 = false;
      try
      {
        List<ZoomChatStruct> newChats = this.Engine.ZoomDatabase.GetNewChats();
        List<ZoomChatStruct> rawChatsToDelete = new List<ZoomChatStruct>();
label_2:
        int num1 = -538716720;
        while (true)
        {
          int num2 = -1873020053;
          uint num3;
          int index;
          bool flag2;
          ZoomChatStruct zoomChatStruct;
          bool flag3;
          bool flag4;
          switch ((num3 = (uint) (num1 ^ num2)) % 19U)
          {
            case 0:
              flag4 = !this.ImportRawChat(zoomChatStruct);
              num1 = (int) num3 * 1425597821 ^ -1122219984;
              continue;
            case 2:
              int num4 = flag3 ? -785275368 : (num4 = -688984960);
              int num5 = (int) num3 * 1396184691;
              num1 = num4 ^ num5;
              continue;
            case 3:
              List<string> stringList = new List<string>();
              index = 0;
              num1 = (int) num3 * 398488313 ^ -732395503;
              continue;
            case 4:
              goto label_2;
            case 5:
              ++index;
              num1 = (int) num3 * 1666288791 ^ 1360277272;
              continue;
            case 6:
              this.Engine.ZoomDatabase.DeleteChats(rawChatsToDelete);
              num1 = (int) num3 * 107737604 ^ -1958547388;
              continue;
            case 7:
              flag2 = index < newChats.Count;
              num1 = -1182236512;
              continue;
            case 8:
              num1 = (int) num3 * 1081672025 ^ 177572441;
              continue;
            case 9:
              ChatManager.\u202B‏‮‬‬‪⁮⁯‎⁯⁪‌⁫‫⁪‪‏⁭‬‭⁬⁬​⁪‬⁫⁪‪‬⁮‭⁬⁭‬‎‭⁪⁭‎⁬‮(CoreObject.log, (object) ChatManager.\u206F⁭‏‬‭‍‏‌‭⁬‫⁯⁬⁪⁯⁮⁫‮⁭​⁮⁮‮​‮⁫‪‬‏‫‎​​‌‫⁮⁯⁫⁯‏‮((object) \u003CModule\u003E.\u200E‏⁯‍‬⁭⁪‌‌‌⁪⁫‫‎⁫‮⁬‎‌⁮⁪⁪⁭‍‌⁫‮‬‎⁬‎‌‎‌⁪‫‬‮⁮‮<string>(1703355923U), (object) zoomChatStruct));
              num1 = (int) num3 * -1111105996 ^ 853140817;
              continue;
            case 10:
              zoomChatStruct = newChats[index];
              num1 = -1342336588;
              continue;
            case 11:
              int num6 = !flag2 ? -750126516 : (num6 = -114686588);
              int num7 = (int) num3 * -74143464;
              num1 = num6 ^ num7;
              continue;
            case 12:
              num1 = (int) num3 * -36443999 ^ 858111753;
              continue;
            case 13:
              flag1 = true;
              num1 = (int) num3 * -1333975437 ^ -1925453585;
              continue;
            case 14:
              this.Engine.ZoomDatabase.DeleteChat(zoomChatStruct);
              num1 = -1933554445;
              continue;
            case 15:
              num1 = (int) num3 * 339631226 ^ 434221450;
              continue;
            case 16:
              flag3 = zoomChatStruct != null;
              num1 = (int) num3 * 1037591174 ^ -1397693489;
              continue;
            case 17:
              int num8 = !flag4 ? -156123985 : (num8 = -816312956);
              int num9 = (int) num3 * -598436872;
              num1 = num8 ^ num9;
              continue;
            case 18:
              num1 = -1813756037;
              continue;
            default:
              goto label_26;
          }
        }
      }
      catch (Exception ex)
      {
label_22:
        int num1 = -656560202;
        while (true)
        {
          int num2 = -1873020053;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * -1543870467 ^ -1139541091;
              continue;
            case 2:
              goto label_22;
            default:
              goto label_25;
          }
        }
label_25:
        ChatManager.\u202B‏‮‬‬‪⁮⁯‎⁯⁪‌⁫‫⁪‪‏⁭‬‭⁬⁬​⁪‬⁫⁪‪‬⁮‭⁬⁭‬‎‭⁪⁭‎⁬‮(CoreObject.log, (object) ex);
      }
label_26:
      return flag1;
    }

    private bool ImportRawChat(ZoomChatStruct rawChat)
    {
      bool flag1 = false;
      try
      {
label_2:
        int num1 = 326178297;
        while (true)
        {
          int num2 = 1063280551;
          uint num3;
          ZoomChat chat;
          bool flag2;
          bool flag3;
          bool flag4;
          switch ((num3 = (uint) (num1 ^ num2)) % 31U)
          {
            case 0:
              flag2 = this.AutoGeneratedMessages.Contains(chat.ChatContent);
              num1 = (int) num3 * -436240492 ^ -1629019166;
              continue;
            case 1:
              num1 = (int) num3 * 1270537741 ^ 2120891269;
              continue;
            case 2:
              num1 = (int) num3 * -1196883164 ^ -291403616;
              continue;
            case 3:
              int num4 = flag2 ? 1222288530 : (num4 = 877889943);
              int num5 = (int) num3 * 224808793;
              num1 = num4 ^ num5;
              continue;
            case 4:
              num1 = (int) num3 * -61575204 ^ -1832090776;
              continue;
            case 5:
              int num6;
              num1 = num6 = !chat.SaveDatabaseObject() ? 1818509173 : (num6 = 1150953012);
              continue;
            case 6:
              num1 = (int) num3 * -1937673134 ^ 2033135033;
              continue;
            case 7:
              num1 = (int) num3 * -2041190310 ^ -1638468675;
              continue;
            case 8:
              int num7 = flag4 ? 1642090486 : (num7 = 1255788240);
              int num8 = (int) num3 * 1807182722;
              num1 = num7 ^ num8;
              continue;
            case 9:
              this.CheckUserNotified(chat);
              num1 = (int) num3 * -1110093730 ^ 1332734639;
              continue;
            case 10:
              num1 = 987023296;
              continue;
            case 11:
              flag4 = chat != null;
              num1 = (int) num3 * -525805985 ^ -592996645;
              continue;
            case 12:
              num1 = 1860480012;
              continue;
            case 13:
              num1 = (int) num3 * -798679600 ^ -1313463700;
              continue;
            case 14:
              chat.AutoGenerated = true;
              num1 = (int) num3 * 1663982419 ^ -1941828787;
              continue;
            case 15:
              flag1 = true;
              num1 = (int) num3 * -2069878931 ^ -1357816407;
              continue;
            case 16:
              ChatManager.\u200D‍‫⁫‌⁫‪⁯‬⁭‮‍​⁯‬‍⁬‭​‫⁫​‪⁬⁪‏‍‍‭‮⁭‮‏⁬‍⁭⁪⁪‮⁬‮(CoreObject.log, (object) \u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(3645594672U));
              num1 = (int) num3 * -903157844 ^ 768592971;
              continue;
            case 18:
              num1 = (int) num3 * 1205547663 ^ -1094222250;
              continue;
            case 19:
              num1 = (int) num3 * 1844835730 ^ 1008499383;
              continue;
            case 20:
              num1 = 645881834;
              continue;
            case 21:
              num1 = (int) num3 * -544443042 ^ -693894750;
              continue;
            case 22:
              goto label_2;
            case 23:
              chat = ZoomFactory.CreateChat(rawChat);
              num1 = (int) num3 * -998404533 ^ 1885845365;
              continue;
            case 24:
              int num9 = !flag3 ? 1074760870 : (num9 = 134871647);
              int num10 = (int) num3 * 1734542413;
              num1 = num9 ^ num10;
              continue;
            case 25:
              num1 = (int) num3 * 2007934229 ^ 676868589;
              continue;
            case 26:
              flag3 = this.IsFloodMessage(rawChat);
              num1 = 417754227;
              continue;
            case 27:
              ChatManager.\u200D‍‫⁫‌⁫‪⁯‬⁭‮‍​⁯‬‍⁬‭​‫⁫​‪⁬⁪‏‍‍‭‮⁭‮‏⁬‍⁭⁪⁪‮⁬‮(CoreObject.log, (object) \u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(150896801U));
              num1 = (int) num3 * 2041648259 ^ 762522203;
              continue;
            case 28:
              this.HandleChatEvent(chat);
              num1 = (int) num3 * -1713154149 ^ 1980155817;
              continue;
            case 29:
              int num11 = !this.PendingChatLinkFound(rawChat) ? 1985655368 : (num11 = 1264784302);
              int num12 = (int) num3 * -2062359064;
              num1 = num11 ^ num12;
              continue;
            case 30:
              num1 = (int) num3 * 770002012 ^ 1577316406;
              continue;
            default:
              goto label_38;
          }
        }
      }
      catch (Exception ex)
      {
label_34:
        int num1 = 580795914;
        while (true)
        {
          int num2 = 1063280551;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              num1 = (int) num3 * 589188966 ^ 1678187505;
              continue;
            case 1:
              ChatManager.\u202B‏‮‬‬‪⁮⁯‎⁯⁪‌⁫‫⁪‪‏⁭‬‭⁬⁬​⁪‬⁫⁪‪‬⁮‭⁬⁭‬‎‭⁪⁭‎⁬‮(CoreObject.log, (object) ex);
              num1 = (int) num3 * 753800034 ^ -105611547;
              continue;
            case 3:
              goto label_34;
            default:
              goto label_38;
          }
        }
      }
label_38:
      bool flag5 = flag1;
label_39:
      int num13 = 949939064;
      while (true)
      {
        int num1 = 1063280551;
        uint num2;
        switch ((num2 = (uint) (num13 ^ num1)) % 3U)
        {
          case 0:
            goto label_39;
          case 1:
            num13 = (int) num2 * 783435462 ^ -357211255;
            continue;
          default:
            goto label_42;
        }
      }
label_42:
      return flag5;
    }

    private bool PendingChatLinkFound(ZoomChatStruct rawChat)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      ChatManager.\u003C\u003Ec__DisplayClass33_0 cDisplayClass330 = new ChatManager.\u003C\u003Ec__DisplayClass33_0();
      // ISSUE: reference to a compiler-generated field
      cDisplayClass330.rawChat = rawChat;
label_1:
      int num1 = -1680717956;
      List<ChatLinkObject> list;
      while (true)
      {
        int num2 = -287474725;
        uint num3;
        bool flag;
        switch ((num3 = (uint) (num1 ^ num2)) % 7U)
        {
          case 0:
            goto label_1;
          case 1:
            // ISSUE: method pointer
            list = ((IEnumerable<ChatLinkObject>) Enumerable.Where<ChatLinkObject>((IEnumerable<M0>) ChatManager.PendingLinkObjects, (Func<M0, bool>) new Func<ChatLinkObject, bool>((object) cDisplayClass330, __methodptr(\u003CPendingChatLinkFound\u003Eb__0)))).ToList<ChatLinkObject>();
            num1 = (int) num3 * 1505689754 ^ 1865881944;
            continue;
          case 2:
            flag = list.Count > 0;
            num1 = (int) num3 * 2002996416 ^ -1736525976;
            continue;
          case 3:
            num1 = (int) num3 * -541999789 ^ -1144128712;
            continue;
          case 4:
            ChatManager.\u206F⁮⁫‮‫⁮‭‎‮⁯⁯⁯‪⁪‬⁯⁫‍⁪‎‮⁮⁭‮‎‌⁪‬‌⁮‌‫⁬‬⁪⁭⁭‍‏⁭‮(CoreObject.log, \u003CModule\u003E.\u200E‏⁯‍‬⁭⁪‌‌‌⁪⁫‫‎⁫‮⁬‎‌⁮⁪⁪⁭‍‌⁫‮‬‎⁬‎‌‎‌⁪‫‬‮⁮‮<string>(2173822517U), new object[0]);
            num1 = (int) num3 * -288424437 ^ -288922214;
            continue;
          case 6:
            if (flag)
            {
              num1 = (int) num3 * -1751699439 ^ 1424441341;
              continue;
            }
            goto label_22;
          default:
            goto label_9;
        }
      }
label_9:
      using (List<ChatLinkObject>.Enumerator enumerator = list.GetEnumerator())
      {
label_15:
        int num2 = enumerator.MoveNext() ? -2144726727 : (num2 = -1544550640);
        while (true)
        {
          int num3 = -287474725;
          uint num4;
          ChatLinkObject current;
          switch ((num4 = (uint) (num2 ^ num3)) % 7U)
          {
            case 0:
              goto label_15;
            case 1:
              current = enumerator.Current;
              num2 = -1880269299;
              continue;
            case 2:
              num2 = (int) num4 * 1068034769 ^ 1090294840;
              continue;
            case 3:
              num2 = (int) num4 * 2064051120 ^ -1401854357;
              continue;
            case 4:
              num2 = -2144726727;
              continue;
            case 6:
              current.Callback.Invoke();
              num2 = (int) num4 * -1044659051 ^ -1042905488;
              continue;
            default:
              goto label_19;
          }
        }
      }
label_19:
      bool flag1 = true;
      goto label_24;
label_22:
      flag1 = false;
      int num5 = -1967694357;
      while (true)
      {
        int num2 = -287474725;
        uint num3;
        switch ((num3 = (uint) (num5 ^ num2)) % 4U)
        {
          case 0:
            num5 = (int) num3 * 1378036912 ^ 243297400;
            continue;
          case 1:
            goto label_22;
          case 2:
            num5 = -1429310486;
            continue;
          default:
            goto label_24;
        }
      }
label_24:
      return flag1;
    }

    private void HandleChatEvent(ZoomChat chat)
    {
      bool messageSent = chat.MessageSent;
label_1:
      int num1 = 578606170;
      while (true)
      {
        int num2 = 2010794451;
        uint num3;
        bool messageReceived;
        switch ((num3 = (uint) (num1 ^ num2)) % 13U)
        {
          case 0:
            goto label_3;
          case 1:
            int num4 = !messageSent ? 1990910883 : (num4 = 1141297896);
            int num5 = (int) num3 * -144867754;
            num1 = num4 ^ num5;
            continue;
          case 2:
            goto label_1;
          case 3:
            ((CompositePresentationEvent<ZoomChat>) this._eventAggregator.GetEvent<ChatSentEvent>()).Publish(chat);
            num1 = (int) num3 * -925177070 ^ 1881729339;
            continue;
          case 4:
            num1 = (int) num3 * 1607830505 ^ 466750292;
            continue;
          case 5:
            num1 = (int) num3 * 243492451 ^ -1645151908;
            continue;
          case 6:
            num1 = (int) num3 * -1620187787 ^ 420965732;
            continue;
          case 7:
            num1 = (int) num3 * 1784783813 ^ -294523555;
            continue;
          case 8:
            messageReceived = chat.MessageReceived;
            num1 = 483023942;
            continue;
          case 9:
            num1 = (int) num3 * 404993536 ^ -1815883644;
            continue;
          case 10:
            ((CompositePresentationEvent<ZoomChat>) this._eventAggregator.GetEvent<ChatReceivedEvent>()).Publish(chat);
            num1 = (int) num3 * 1016175099 ^ -990290546;
            continue;
          case 11:
            num1 = (int) num3 * -991193369 ^ 2062150899;
            continue;
          case 12:
            int num6 = messageReceived ? -1739945930 : (num6 = -925815153);
            int num7 = (int) num3 * 1025195807;
            num1 = num6 ^ num7;
            continue;
          default:
            goto label_15;
        }
      }
label_15:
      return;
label_3:;
    }

    private bool IsFloodMessage(ZoomChatStruct rawChat)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      ChatManager.\u003C\u003Ec__DisplayClass35_0 cDisplayClass350 = new ChatManager.\u003C\u003Ec__DisplayClass35_0();
label_1:
      int num1 = 236201622;
      bool flag1;
      while (true)
      {
        int num2 = 1584373858;
        uint num3;
        bool flag2;
        List<ZoomChat> list;
        bool flag3;
        // ISSUE: variable of a compiler-generated type
        ChatManager.\u003C\u003Ec__DisplayClass35_1 cDisplayClass351;
        bool flag4;
        switch ((num3 = (uint) (num1 ^ num2)) % 23U)
        {
          case 0:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass351.CS\u0024\u003C\u003E8__locals1 = cDisplayClass350;
            num1 = (int) num3 * -996459177 ^ -1650860570;
            continue;
          case 1:
            flag2 = false;
            num1 = (int) num3 * 2123624583 ^ -448259650;
            continue;
          case 2:
            flag4 = flag2;
            num1 = 2016796849;
            continue;
          case 3:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass350.\u003C\u003E4__this = this;
            num1 = (int) num3 * 1640882184 ^ 1357237360;
            continue;
          case 4:
            num1 = 1572759524;
            continue;
          case 5:
            flag1 = flag2;
            num1 = 708509166;
            continue;
          case 6:
            // ISSUE: reference to a compiler-generated field
            // ISSUE: reference to a compiler-generated field
            // ISSUE: reference to a compiler-generated field
            cDisplayClass351.chatTime = StringHelper.UnixTimeStampToDateTime(cDisplayClass351.CS\u0024\u003C\u003E8__locals1.rawChat.time);
            num1 = (int) num3 * 1435771024 ^ 1856958737;
            continue;
          case 8:
            int num4 = !flag4 ? 48010266 : (num4 = 2097496136);
            int num5 = (int) num3 * -1878931312;
            num1 = num4 ^ num5;
            continue;
          case 9:
            num1 = (int) num3 * -1896549765 ^ -277948486;
            continue;
          case 10:
            num1 = (int) num3 * 598767860 ^ -773643885;
            continue;
          case 11:
            // ISSUE: reference to a compiler-generated field
            this.Engine.SetUserAsFlooding(cDisplayClass350.rawChat.senderName);
            num1 = (int) num3 * 946979630 ^ 1718654069;
            continue;
          case 12:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass350.rawChat = rawChat;
            num1 = (int) num3 * 288049027 ^ -336773720;
            continue;
          case 13:
            int num6 = this.Engine.ActiveMeeting == null ? -1546962956 : (num6 = -1473499590);
            int num7 = (int) num3 * -295121114;
            num1 = num6 ^ num7;
            continue;
          case 14:
            // ISSUE: object of a compiler-generated type is created
            cDisplayClass351 = new ChatManager.\u003C\u003Ec__DisplayClass35_1();
            num1 = (int) num3 * 1110430510 ^ 281890052;
            continue;
          case 15:
            num1 = (int) num3 * 1377982699 ^ 1794010533;
            continue;
          case 16:
            flag2 = true;
            num1 = (int) num3 * -671840923 ^ -2067941824;
            continue;
          case 17:
            num1 = (int) num3 * 1359260723 ^ -403237165;
            continue;
          case 18:
            num1 = (int) num3 * 2138234334 ^ -1775960712;
            continue;
          case 19:
            int num8 = !flag3 ? -1149861350 : (num8 = -690699533);
            int num9 = (int) num3 * 1576533888;
            num1 = num8 ^ num9;
            continue;
          case 20:
            // ISSUE: method pointer
            list = ((IEnumerable<ZoomChat>) Enumerable.Where<ZoomChat>((IEnumerable<M0>) this.Engine.ActiveMeeting.CurrentChats, (Func<M0, bool>) new Func<ZoomChat, bool>((object) cDisplayClass351, __methodptr(\u003CIsFloodMessage\u003Eb__0)))).ToList<ZoomChat>();
            num1 = (int) num3 * -1381825707 ^ -1292212731;
            continue;
          case 21:
            goto label_1;
          case 22:
            flag3 = list.Count > 5;
            num1 = (int) num3 * 1053701242 ^ 424533044;
            continue;
          default:
            goto label_24;
        }
      }
label_24:
      return flag1;
    }

    internal bool IsFloodMessage(ZoomChat chat)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      ChatManager.\u003C\u003Ec__DisplayClass36_0 cDisplayClass360 = new ChatManager.\u003C\u003Ec__DisplayClass36_0();
label_1:
      int num1 = 1248096704;
      bool flag1;
      while (true)
      {
        int num2 = 1869133526;
        uint num3;
        bool flag2;
        bool flag3;
        bool flag4;
        List<ZoomChat> list;
        switch ((num3 = (uint) (num1 ^ num2)) % 18U)
        {
          case 0:
            num1 = (int) num3 * -1131936584 ^ -338703135;
            continue;
          case 1:
            num1 = (int) num3 * -1100570489 ^ -643041831;
            continue;
          case 2:
            flag3 = flag2;
            num1 = 932388599;
            continue;
          case 3:
            int num4 = !flag3 ? -1247417053 : (num4 = -1853081835);
            int num5 = (int) num3 * -546771598;
            num1 = num4 ^ num5;
            continue;
          case 4:
            // ISSUE: reference to a compiler-generated field
            this.Engine.SetUserAsFlooding(cDisplayClass360.chat.SendingZoomId);
            num1 = (int) num3 * 1138269461 ^ 1187905808;
            continue;
          case 5:
            int num6 = list.Count > 5 ? 1938157723 : (num6 = 1121841562);
            int num7 = (int) num3 * 581069191;
            num1 = num6 ^ num7;
            continue;
          case 6:
            int num8 = flag4 ? 1374312703 : (num8 = 1027936308);
            int num9 = (int) num3 * -1563419696;
            num1 = num8 ^ num9;
            continue;
          case 8:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass360.chat = chat;
            num1 = (int) num3 * -33009189 ^ -2088161767;
            continue;
          case 9:
            goto label_1;
          case 10:
            flag4 = this.Engine.ActiveMeeting != null;
            num1 = (int) num3 * 769830729 ^ 1082168142;
            continue;
          case 11:
            num1 = 1595111252;
            continue;
          case 12:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass360.\u003C\u003E4__this = this;
            num1 = (int) num3 * 1547288967 ^ 958464964;
            continue;
          case 13:
            flag1 = flag2;
            num1 = 999090061;
            continue;
          case 14:
            // ISSUE: method pointer
            list = ((IEnumerable<ZoomChat>) Enumerable.Where<ZoomChat>((IEnumerable<M0>) this.Engine.ActiveMeeting.CurrentChats, (Func<M0, bool>) new Func<ZoomChat, bool>((object) cDisplayClass360, __methodptr(\u003CIsFloodMessage\u003Eb__0)))).ToList<ZoomChat>();
            num1 = (int) num3 * -474700003 ^ -1853778709;
            continue;
          case 15:
            num1 = (int) num3 * -1624372375 ^ 1287485979;
            continue;
          case 16:
            flag2 = true;
            num1 = (int) num3 * 142937645 ^ 1356583455;
            continue;
          case 17:
            flag2 = false;
            num1 = (int) num3 * 496831984 ^ -500462656;
            continue;
          default:
            goto label_19;
        }
      }
label_19:
      return flag1;
    }

    private void CheckForFlood(ZoomChat chat)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      ChatManager.\u003C\u003Ec__DisplayClass37_0 cDisplayClass370 = new ChatManager.\u003C\u003Ec__DisplayClass37_0();
label_1:
      int num1 = -1161433202;
      while (true)
      {
        int num2 = -1318021161;
        uint num3;
        bool flag1;
        bool flag2;
        switch ((num3 = (uint) (num1 ^ num2)) % 12U)
        {
          case 0:
            num1 = (int) num3 * -727412963 ^ 1350941464;
            continue;
          case 1:
            int num4 = !flag2 ? 966873075 : (num4 = 1471902070);
            int num5 = (int) num3 * -1745418226;
            num1 = num4 ^ num5;
            continue;
          case 2:
            num1 = (int) num3 * -953668337 ^ 2137897246;
            continue;
          case 3:
            num1 = (int) num3 * -1105655836 ^ -583922935;
            continue;
          case 4:
            int num6 = !flag1 ? 1098526656 : (num6 = 1715073071);
            int num7 = (int) num3 * 1639569553;
            num1 = num6 ^ num7;
            continue;
          case 5:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass370.\u003C\u003E4__this = this;
            // ISSUE: reference to a compiler-generated field
            cDisplayClass370.chat = chat;
            num1 = (int) num3 * -2011391250 ^ -373651415;
            continue;
          case 6:
            goto label_3;
          case 7:
            flag2 = this.Engine.ActiveMeeting != null;
            num1 = (int) num3 * 231736215 ^ -1140447885;
            continue;
          case 8:
            Engine engine = this.Engine;
            // ISSUE: reference to a compiler-generated field
            RemoveUser removeUser = new RemoveUser(cDisplayClass370.chat.SendingZoomId);
            int num8 = 1;
            removeUser.AutoGenerated = num8 != 0;
            string callerName = \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(4267356687U);
            engine.AddActivity((ActivityBase) removeUser, callerName);
            num1 = (int) num3 * 990452063 ^ -191590739;
            continue;
          case 9:
            goto label_1;
          case 10:
            // ISSUE: method pointer
            flag1 = ((IEnumerable<ZoomChat>) Enumerable.Where<ZoomChat>((IEnumerable<M0>) this.Engine.ActiveMeeting.CurrentChats, (Func<M0, bool>) new Func<ZoomChat, bool>((object) cDisplayClass370, __methodptr(\u003CCheckForFlood\u003Eb__0)))).ToList<ZoomChat>().Count > 1;
            num1 = (int) num3 * -1089815745 ^ -913443247;
            continue;
          case 11:
            num1 = -1785625563;
            continue;
          default:
            goto label_14;
        }
      }
label_14:
      return;
label_3:;
    }

    private void Initialize()
    {
      string sZoomName = string.Empty;
      string sZoomEmail = string.Empty;
label_1:
      int num1 = -1836948569;
      object chatLocker;
      while (true)
      {
        int num2 = -1410429952;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 0:
            goto label_1;
          case 1:
            chatLocker = ChatManager.chatLocker;
            num1 = (int) num3 * -1863222466 ^ 1321788009;
            continue;
          default:
            goto label_4;
        }
      }
label_4:
      bool flag1 = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(chatLocker, ref flag1);
label_6:
        int num2 = -1150236189;
        while (true)
        {
          int num3 = -1410429952;
          uint num4;
          bool flag2;
          bool flag3;
          switch ((num4 = (uint) (num2 ^ num3)) % 13U)
          {
            case 0:
              num2 = (int) num4 * -1200760601 ^ 1500157581;
              continue;
            case 1:
              flag2 = !this.Engine.ZoomDatabase.GetZoomNames(out sZoomName, out sZoomEmail);
              num2 = (int) num4 * -918645543 ^ -1175965228;
              continue;
            case 2:
              int num5 = !flag2 ? 1616875009 : (num5 = 2045945704);
              int num6 = (int) num4 * 2041911488;
              num2 = num5 ^ num6;
              continue;
            case 3:
              flag3 = !ChatManager.\u202B‭‌⁮‍⁪⁫⁬‫‮⁫⁪‮‌‌‫‍⁭‬‍‬⁪‫‪‌‍‏​‬⁫⁫⁭⁪‎⁬⁯‏‮​‏‮(sZoomName, this.Engine.CurrentName);
              num2 = -1051704544;
              continue;
            case 4:
              goto label_11;
            case 5:
              goto label_23;
            case 6:
              this.Engine.CurrentName = sZoomName;
              num2 = (int) num4 * 1359759257 ^ -1685450113;
              continue;
            case 7:
              num2 = (int) num4 * -1247620555 ^ -386118868;
              continue;
            case 8:
              goto label_6;
            case 9:
              num2 = (int) num4 * -1042082309 ^ 1830895658;
              continue;
            case 10:
              int num7 = !flag3 ? -1683376812 : (num7 = -376779806);
              int num8 = (int) num4 * -803431325;
              num2 = num7 ^ num8;
              continue;
            case 11:
              this.AutoGeneratedMessages = new List<string>();
              this.Initialized = true;
              num2 = -1858629379;
              continue;
            case 12:
              num2 = (int) num4 * -1484622473 ^ 601489317;
              continue;
            default:
              goto label_19;
          }
        }
label_19:
        return;
label_23:
        return;
label_11:
        throw ChatManager.\u206D⁯‪⁫⁭‌‪⁮⁪​⁪⁪⁭⁪‍‪‌‏‫⁪⁬⁬‬⁬‭⁮⁪⁫‌⁯⁫‎⁭⁪‌⁬⁮‭⁭‮‮(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3919485410U));
      }
      finally
      {
        if (flag1)
        {
label_21:
          int num2 = -592797305;
          while (true)
          {
            int num3 = -1410429952;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 3U)
            {
              case 1:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(chatLocker);
                num2 = (int) num4 * -199386459 ^ 392708477;
                continue;
              case 2:
                goto label_21;
              default:
                goto label_25;
            }
          }
        }
label_25:;
      }
    }

    private void ManageVideoChatLinks()
    {
    }

    internal void ResetUserNotifications()
    {
label_1:
      int num1 = -1907800829;
      object chatLocker;
      while (true)
      {
        int num2 = -1703568057;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 1:
            chatLocker = ChatManager.chatLocker;
            num1 = (int) num3 * -1006065517 ^ -10273664;
            continue;
          case 2:
            goto label_1;
          default:
            goto label_4;
        }
      }
label_4:
      bool flag = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(chatLocker, ref flag);
        this.notifiedUserNames.Clear();
label_6:
        int num2 = -78274653;
        while (true)
        {
          int num3 = -1703568057;
          uint num4;
          switch ((num4 = (uint) (num2 ^ num3)) % 3U)
          {
            case 0:
              goto label_6;
            case 1:
              goto label_13;
            case 2:
              num2 = (int) num4 * 496534704 ^ 639852719;
              continue;
            default:
              goto label_9;
          }
        }
label_9:
        return;
label_13:;
      }
      finally
      {
        if (flag)
        {
label_11:
          int num2 = -441056154;
          while (true)
          {
            int num3 = -1703568057;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 4U)
            {
              case 0:
                goto label_11;
              case 1:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(chatLocker);
                num2 = (int) num4 * 1232203417 ^ -999983932;
                continue;
              case 2:
                num2 = (int) num4 * -1973218325 ^ 1602931070;
                continue;
              default:
                goto label_16;
            }
          }
        }
label_16:;
      }
    }

    private void CheckUserNotified(ZoomChat chat)
    {
label_1:
      int num1 = 1311315768;
      bool flag1;
      while (true)
      {
        int num2 = 1195192418;
        uint num3;
        string str;
        bool wasRecipient;
        bool flag2;
        string message;
        int num4;
        int num5;
        switch ((num3 = (uint) (num1 ^ num2)) % 36U)
        {
          case 0:
            num1 = (int) num3 * 334639520 ^ -1728192879;
            continue;
          case 1:
            int num6 = !flag2 ? -591893641 : (num6 = -1352652680);
            int num7 = (int) num3 * 775985510;
            num1 = num6 ^ num7;
            continue;
          case 2:
            num1 = (int) num3 * -2061663328 ^ -290577699;
            continue;
          case 3:
            message = ChatManager.\u200B‍‌‪‪⁬‎‭‭‪⁪⁪⁫‍‬⁭‫‍‬‬‬​‏‎‍‍‮‌‌⁭‎‪‌⁯⁭‌⁭​⁬‬‮(\u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(1332995260U), (object) ChatManager.\u202D⁭‍‏⁮⁯⁪⁬‭‪‎‏⁪⁯⁫⁫‍‬⁮‫⁭⁭⁭⁫‍‬​​⁮‮⁫⁬​‮‎⁯⁯‍‮‪‮(this.Engine.Settings.AutoRespondBlockedUserMessage), (object) str);
            num1 = 1208144212;
            continue;
          case 4:
            str = ChatManager.\u206B‮⁪⁪‏⁯‫‏‭​⁬‭‎​‏⁭‭‭⁭⁫⁯‫‎‏‭‬‍⁯​‭‮‪​‬⁬‪‍‏‌‌‮(ChatManager.\u202D‪​​​‌⁭‬‪‪⁫‍⁯‮⁫‍⁭‪‍‮‪‭‏‬‏​‬⁭‏‫‭​⁯⁫‎⁭⁭⁭⁯‎‮(str, 0, 30), \u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(569968142U));
            num1 = (int) num3 * -6590547 ^ -651895899;
            continue;
          case 5:
            num1 = 1333007205;
            continue;
          case 6:
            Engine engine = this.Engine;
            SendChat sendChat = new SendChat(message, chat.SendingZoomId);
            int num8 = 1;
            sendChat.AutoGenerated = num8 != 0;
            string callerName = \u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3494884208U);
            engine.AddActivity((ActivityBase) sendChat, callerName);
            this.Trace(TraceType.Chat, \u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(2280899643U), (object) chat.SendingZoomId);
            num1 = (int) num3 * -1852323108 ^ -594554633;
            continue;
          case 7:
            num1 = (int) num3 * 1312048992 ^ 873786775;
            continue;
          case 8:
            int num9 = this.Engine.Settings.AutoRespondBlockedUser ? 812300063 : (num9 = 2098182942);
            int num10 = (int) num3 * 12295437;
            num1 = num9 ^ num10;
            continue;
          case 9:
            num1 = (int) num3 * 1387338473 ^ 1167052602;
            continue;
          case 10:
            if (this.Engine.Settings.AutoResponderEnabled)
            {
              num1 = 1295878680;
              continue;
            }
            goto label_68;
          case 11:
            num1 = 1773885367;
            continue;
          case 12:
            num1 = 879818171;
            continue;
          case 13:
            num1 = (int) num3 * 1186979688 ^ -1970741606;
            continue;
          case 14:
            num1 = (int) num3 * 1531176800 ^ 1073655200;
            continue;
          case 15:
            num1 = (int) num3 * 1643279080 ^ 1806911999;
            continue;
          case 16:
            num1 = (int) num3 * -380656951 ^ 825251997;
            continue;
          case 17:
            int num11 = wasRecipient ? 474595255 : (num11 = 1724689185);
            int num12 = (int) num3 * 1020535498;
            num1 = num11 ^ num12;
            continue;
          case 18:
            num1 = (int) num3 * 178771100 ^ 1578163908;
            continue;
          case 19:
            str = chat.ChatContent;
            num1 = (int) num3 * -414128452 ^ 348064766;
            continue;
          case 20:
            goto label_1;
          case 21:
            this.Trace(TraceType.Chat, \u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3578876569U));
            num1 = (int) num3 * -921431867 ^ 1832690285;
            continue;
          case 22:
            this.Trace(TraceType.Chat, \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(236222699U), (object) chat.SendingZoomId);
            num1 = 205541104;
            continue;
          case 24:
            if (!ChatManager.\u206D‫‌‍⁫‍⁪⁭‫‌‍​‬⁭⁫⁪⁪⁫‬⁯‎‌‍⁯‭⁭‪‪⁬‪‏‭⁮‫⁯‍⁬‍‭‍‮(str))
            {
              num4 = 0;
              break;
            }
            num1 = (int) num3 * -520783259 ^ 2044992958;
            continue;
          case 25:
            num1 = 222403517;
            continue;
          case 26:
            flag1 = false;
            num1 = (int) num3 * -966777790 ^ -1891156074;
            continue;
          case 27:
            this.Trace(TraceType.Chat, \u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(3103989159U), (object) chat.CurrentName, (object) chat.ReceivingZoomId, (object) chat.SendingZoomId);
            num1 = (int) num3 * 585000523 ^ -1139339764;
            continue;
          case 28:
            num4 = ChatManager.\u202E‍‎‎‮‎⁬‬⁬‌‫‫‏‮‌‌‪⁫‪‏‭⁫‭⁯‏‪⁫​⁭​‫‍⁬‫‍⁮‪⁫‬‪‮(str) > 30 ? 1 : 0;
            break;
          case 29:
            wasRecipient = chat.WasRecipient;
            num1 = (int) num3 * -751704859 ^ 1964176078;
            continue;
          case 30:
            if (ChatManager.\u202B‭‌⁮‍⁪⁫⁬‫‮⁫⁪‮‌‌‫‍⁭‬‍‬⁪‫‪‌‍‏​‬⁫⁫⁭⁪‎⁬⁯‏‮​‏‮(chat.ReceivingZoomId, chat.CurrentName))
            {
              num1 = (int) num3 * 1270108266 ^ 1036395997;
              continue;
            }
            num5 = 0;
            goto label_32;
          case 31:
            num1 = (int) num3 * -2042666346 ^ 311130454;
            continue;
          case 32:
            num1 = (int) num3 * 885062390 ^ -1232606346;
            continue;
          case 33:
            int num13 = !ChatManager.\u200B‍‫‫⁬‮⁪⁬⁪⁮‮⁯‮⁯‫‫⁮‭⁬‎⁫⁮‭​‬⁪⁪⁬⁭‏‬​‎‍⁫‭⁪‭⁯⁬‮(this.Engine.Settings.AutoRespondBlockedUserList, ChatManager.\u202B⁮‌‫‍‪‮⁫‫‬‭‏‎‎‎⁪‭‌⁫⁮⁬⁬‬⁮⁬⁬⁫‪‮‍‍⁫⁯‌⁪‎‏‍‭‭‮(chat.SendingZoomId)) ? -2115604230 : (num13 = -1017422942);
            int num14 = (int) num3 * -1090809298;
            num1 = num13 ^ num14;
            continue;
          case 34:
            num1 = (int) num3 * -2032707118 ^ 467325161;
            continue;
          case 35:
            num5 = !ChatManager.\u202B‭‌⁮‍⁪⁫⁬‫‮⁫⁪‮‌‌‫‍⁭‬‍‬⁪‫‪‌‍‏​‬⁫⁫⁭⁪‎⁬⁯‏‮​‏‮(chat.ReceivingUserId, \u003CModule\u003E.\u200E‏⁯‍‬⁭⁪‌‌‌⁪⁫‫‎⁫‮⁬‎‌⁮⁪⁪⁭‍‌⁫‮‬‎⁬‎‌‎‌⁪‫‬‮⁮‮<string>(2973092196U)) ? 1 : 0;
            goto label_32;
          default:
            goto label_45;
        }
        flag2 = num4 != 0;
        num1 = 1485478575;
        continue;
label_32:
        if (num5 != 0)
          num1 = 781198558;
        else
          goto label_76;
      }
label_68:
      return;
label_45:
      object chatLocker = ChatManager.chatLocker;
      bool flag3 = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(chatLocker, ref flag3);
label_47:
        int num2 = 2145224685;
        while (true)
        {
          int num3 = 1195192418;
          uint num4;
          bool flag2;
          switch ((num4 = (uint) (num2 ^ num3)) % 11U)
          {
            case 0:
              flag2 = !this.notifiedUserNames.Contains(chat.SendingZoomId);
              num2 = (int) num4 * 329197218 ^ 1824506360;
              continue;
            case 1:
              int num5 = flag2 ? 724407617 : (num5 = 1013444345);
              int num6 = (int) num4 * 1039104237;
              num2 = num5 ^ num6;
              continue;
            case 2:
              num2 = (int) num4 * 2061910343 ^ -477954057;
              continue;
            case 4:
              this.notifiedUserNames.Add(chat.SendingZoomId);
              num2 = (int) num4 * 754954452 ^ -521429593;
              continue;
            case 5:
              flag1 = true;
              num2 = (int) num4 * -1278438823 ^ -1206613761;
              continue;
            case 6:
              num2 = (int) num4 * 481955260 ^ 1612655425;
              continue;
            case 7:
              num2 = (int) num4 * -1685392988 ^ -1664967509;
              continue;
            case 8:
              goto label_47;
            case 9:
              num2 = (int) num4 * -548295624 ^ -270172564;
              continue;
            case 10:
              num2 = 936124541;
              continue;
            default:
              goto label_70;
          }
        }
      }
      finally
      {
        if (flag3)
        {
label_59:
          int num2 = 151331855;
          while (true)
          {
            int num3 = 1195192418;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 4U)
            {
              case 0:
                num2 = (int) num4 * 76257550 ^ 1033389429;
                continue;
              case 1:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(chatLocker);
                num2 = (int) num4 * -1584167379 ^ 1495536511;
                continue;
              case 2:
                goto label_59;
              default:
                goto label_64;
            }
          }
        }
label_64:;
      }
label_67:
      bool flag4;
      int num15;
      while (true)
      {
        int num2 = 1195192418;
        uint num3;
        switch ((num3 = (uint) (num15 ^ num2)) % 13U)
        {
          case 0:
            goto label_65;
          case 1:
            this.notifiedUserNames.Add(chat.ReceivingZoomId);
            num15 = (int) num3 * -1773741650 ^ -895815627;
            continue;
          case 2:
            ChatManager.\u206C⁫⁮⁬‎⁫‭⁯‍‍⁮​⁮⁫⁯⁮‪⁭⁯‭⁬‌‪‮⁭⁬⁪⁯‌‫‍‬‪⁯‭‭​‎⁮⁭‮(CoreObject.log, \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(599883362U), (object) chat.SendingZoomId);
            Engine engine = this.Engine;
            SendChat sendChat = new SendChat(this.Engine.Settings.AutoResponderMessage, chat.SendingZoomId);
            int num4 = 1;
            sendChat.AutoGenerated = num4 != 0;
            string callerName = \u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(2477535937U);
            engine.AddActivity((ActivityBase) sendChat, callerName);
            num15 = (int) num3 * -474565216 ^ -759149776;
            continue;
          case 3:
            num15 = (int) num3 * -1399821323 ^ 2086048395;
            continue;
          case 4:
            num15 = (int) num3 * -1168702186 ^ 1433162339;
            continue;
          case 5:
            int num5 = !this.notifiedUserNames.Contains(chat.ReceivingZoomId) ? 1800537505 : (num5 = 229107051);
            int num6 = (int) num3 * -915824674;
            num15 = num5 ^ num6;
            continue;
          case 6:
            goto label_76;
          case 7:
            num15 = 10633084;
            continue;
          case 8:
            num15 = 60875180;
            continue;
          case 9:
            num15 = 118960614;
            continue;
          case 10:
            num15 = (int) num3 * 1188106939 ^ 250771024;
            continue;
          case 11:
            goto label_70;
          case 12:
            int num7 = flag4 ? 1715351871 : (num7 = 1214607200);
            int num8 = (int) num3 * -572471673;
            num15 = num7 ^ num8;
            continue;
          default:
            goto label_61;
        }
      }
label_61:
      return;
label_65:
      return;
label_70:
      num15 = flag1 ? 446305636 : (num15 = 1456739313);
      goto label_67;
label_76:
      flag4 = ChatManager.\u202B‭‌⁮‍⁪⁫⁬‫‮⁫⁪‮‌‌‫‍⁭‬‍‬⁪‫‪‌‍‏​‬⁫⁫⁭⁪‎⁬⁯‏‮​‏‮(chat.SendingZoomId, this.Engine.CurrentName);
      num15 = 1359784550;
      goto label_67;
    }

    private void AddChatLinkEvent(ChatLinkObject obj)
    {
    }

    private void AddAutoGeneratedMessage(ZoomChat obj)
    {
      object managerLock = ManagerBase.managerLock;
      bool flag1 = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(managerLock, ref flag1);
label_2:
        int num1 = -1126611127;
        while (true)
        {
          int num2 = -1403850129;
          uint num3;
          bool flag2;
          switch ((num3 = (uint) (num1 ^ num2)) % 9U)
          {
            case 0:
              goto label_2;
            case 1:
              num1 = (int) num3 * 755622130 ^ -1112846439;
              continue;
            case 2:
              this.AutoGeneratedMessages.Add(obj.ChatContent);
              num1 = (int) num3 * -1452801894 ^ -107074357;
              continue;
            case 3:
              goto label_15;
            case 4:
              flag2 = !this.AutoGeneratedMessages.Contains(obj.ChatContent);
              num1 = (int) num3 * -1706865553 ^ 52339123;
              continue;
            case 5:
              num1 = (int) num3 * 134005010 ^ 1402276490;
              continue;
            case 6:
              int num4 = flag2 ? -2010356055 : (num4 = -1521674890);
              int num5 = (int) num3 * -403570898;
              num1 = num4 ^ num5;
              continue;
            case 7:
              num1 = -809758742;
              continue;
            case 8:
              num1 = (int) num3 * -1004721830 ^ -2026379776;
              continue;
            default:
              goto label_11;
          }
        }
label_11:
        return;
label_15:;
      }
      finally
      {
        if (flag1)
        {
label_13:
          int num1 = -1464196215;
          while (true)
          {
            int num2 = -1403850129;
            uint num3;
            switch ((num3 = (uint) (num1 ^ num2)) % 4U)
            {
              case 0:
                goto label_13;
              case 1:
                num1 = (int) num3 * 1307922012 ^ -2037689516;
                continue;
              case 2:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(managerLock);
                num1 = (int) num3 * 203495147 ^ -1434988532;
                continue;
              default:
                goto label_18;
            }
          }
        }
label_18:;
      }
    }

    private void RemoveAutoGeneratedMessage(string message)
    {
      object managerLock = ManagerBase.managerLock;
      bool flag1 = false;
      try
      {
        ChatManager.\u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮(managerLock, ref flag1);
label_2:
        int num1 = 724279389;
        while (true)
        {
          int num2 = 1514267359;
          uint num3;
          bool flag2;
          switch ((num3 = (uint) (num1 ^ num2)) % 6U)
          {
            case 0:
              goto label_2;
            case 1:
              num1 = 324267776;
              continue;
            case 2:
              int num4 = !flag2 ? -611044706 : (num4 = -967116882);
              int num5 = (int) num3 * -966180374;
              num1 = num4 ^ num5;
              continue;
            case 3:
              goto label_12;
            case 4:
              flag2 = this.AutoGeneratedMessages.Contains(message);
              num1 = (int) num3 * -1617369469 ^ -1045774159;
              continue;
            case 5:
              this.AutoGeneratedMessages.Remove(message);
              num1 = (int) num3 * -824510563 ^ -1860378125;
              continue;
            default:
              goto label_8;
          }
        }
label_8:
        return;
label_12:;
      }
      finally
      {
        if (flag1)
        {
label_10:
          int num1 = 1798781303;
          while (true)
          {
            int num2 = 1514267359;
            uint num3;
            switch ((num3 = (uint) (num1 ^ num2)) % 3U)
            {
              case 0:
                goto label_10;
              case 2:
                ChatManager.\u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮(managerLock);
                num1 = (int) num3 * 855206527 ^ 1508572295;
                continue;
              default:
                goto label_14;
            }
          }
        }
label_14:;
      }
    }

    static void \u206A‬‏‍⁬⁬⁪‌⁪⁭‏‬​‎⁫‎‪‬‫‌‏⁮‏⁪‍‬‬‬​‭‬‎⁪‏⁪‬⁯⁯‌⁪‮([In] object obj0, [In] ref bool obj1)
    {
      Monitor.Enter(obj0, ref obj1);
    }

    static void \u206D‎‬‌⁭‭​⁭‮⁬‮‪⁪​‪​⁪‏​⁭⁯‭⁮⁯‮‬‫‌‬⁮‬‎⁪⁬‪⁭⁬⁭‪⁮‮([In] object obj0)
    {
      Monitor.Exit(obj0);
    }

    static void \u200F⁬‏‎‏⁯⁬‭⁬‮‎⁮‪⁯‬⁫⁬‬‏‍⁭⁬‬​⁫⁪⁬‮‏‫⁯‫‌⁯⁬‫‮‎⁫‮‮([In] int obj0)
    {
      Thread.Sleep(obj0);
    }

    static void \u202B‏‮‬‬‪⁮⁯‎⁯⁪‌⁫‫⁪‪‏⁭‬‭⁬⁬​⁪‬⁫⁪‪‬⁮‭⁬⁭‬‎‭⁪⁭‎⁬‮([In] ILog obj0, [In] object obj1)
    {
      obj0.Error(obj1);
    }

    static string \u206F⁭‏‬‭‍‏‌‭⁬‫⁯⁬⁪⁯⁮⁫‮⁭​⁮⁮‮​‮⁫‪‬‏‫‎​​‌‫⁮⁯⁫⁯‏‮([In] object obj0, [In] object obj1)
    {
      return obj0.ToString() + obj1;
    }

    static void \u200D‍‫⁫‌⁫‪⁯‬⁭‮‍​⁯‬‍⁬‭​‫⁫​‪⁬⁪‏‍‍‭‮⁭‮‏⁬‍⁭⁪⁪‮⁬‮([In] ILog obj0, [In] object obj1)
    {
      obj0.Info(obj1);
    }

    static void \u206F⁮⁫‮‫⁮‭‎‮⁯⁯⁯‪⁪‬⁯⁫‍⁪‎‮⁮⁭‮‎‌⁪‬‌⁮‌‫⁬‬⁪⁭⁭‍‏⁭‮([In] ILog obj0, [In] string obj1, [In] object[] obj2)
    {
      obj0.DebugFormat(obj1, obj2);
    }

    static Exception \u206D⁯‪⁫⁭‌‪⁮⁪​⁪⁪⁭⁪‍‪‌‏‫⁪⁬⁬‬⁬‭⁮⁪⁫‌⁯⁫‎⁭⁪‌⁬⁮‭⁭‮‮([In] string obj0)
    {
      return new Exception(obj0);
    }

    static bool \u202B‭‌⁮‍⁪⁫⁬‫‮⁫⁪‮‌‌‫‍⁭‬‍‬⁪‫‪‌‍‏​‬⁫⁫⁭⁪‎⁬⁯‏‮​‏‮([In] string obj0, [In] string obj1)
    {
      return obj0.Equals(obj1);
    }

    static string \u202B⁮‌‫‍‪‮⁫‫‬‭‏‎‎‎⁪‭‌⁫⁮⁬⁬‬⁮⁬⁬⁫‪‮‍‍⁫⁯‌⁪‎‏‍‭‭‮([In] string obj0)
    {
      return obj0.ToUpper();
    }

    static bool \u200B‍‫‫⁬‮⁪⁬⁪⁮‮⁯‮⁯‫‫⁮‭⁬‎⁫⁮‭​‬⁪⁪⁬⁭‏‬​‎‍⁫‭⁪‭⁯⁬‮([In] string obj0, [In] string obj1)
    {
      return obj0.Contains(obj1);
    }

    static bool \u206D‫‌‍⁫‍⁪⁭‫‌‍​‬⁭⁫⁪⁪⁫‬⁯‎‌‍⁯‭⁭‪‪⁬‪‏‭⁮‫⁯‍⁬‍‭‍‮([In] string obj0)
    {
      return string.IsNullOrEmpty(obj0);
    }

    static int \u202E‍‎‎‮‎⁬‬⁬‌‫‫‏‮‌‌‪⁫‪‏‭⁫‭⁯‏‪⁫​⁭​‫‍⁬‫‍⁮‪⁫‬‪‮([In] string obj0)
    {
      return obj0.Length;
    }

    static string \u202D‪​​​‌⁭‬‪‪⁫‍⁯‮⁫‍⁭‪‍‮‪‭‏‬‏​‬⁭‏‫‭​⁯⁫‎⁭⁭⁭⁯‎‮([In] string obj0, [In] int obj1, [In] int obj2)
    {
      return obj0.Substring(obj1, obj2);
    }

    static string \u206B‮⁪⁪‏⁯‫‏‭​⁬‭‎​‏⁭‭‭⁭⁫⁯‫‎‏‭‬‍⁯​‭‮‪​‬⁬‪‍‏‌‌‮([In] string obj0, [In] string obj1)
    {
      return obj0 + obj1;
    }

    static string \u202D⁭‍‏⁮⁯⁪⁬‭‪‎‏⁪⁯⁫⁫‍‬⁮‫⁭⁭⁭⁫‍‬​​⁮‮⁫⁬​‮‎⁯⁯‍‮‪‮([In] string obj0)
    {
      return obj0.Trim();
    }

    static string \u200B‍‌‪‪⁬‎‭‭‪⁪⁪⁫‍‬⁭‫‍‬‬‬​‏‎‍‍‮‌‌⁭‎‪‌⁯⁭‌⁭​⁬‬‮([In] string obj0, [In] object obj1, [In] object obj2)
    {
      return string.Format(obj0, obj1, obj2);
    }

    static void \u206C⁫⁮⁬‎⁫‭⁯‍‍⁮​⁮⁫⁯⁮‪⁭⁯‭⁬‌‪‮⁭⁬⁪⁯‌‫‍‬‪⁯‭‭​‎⁮⁭‮([In] ILog obj0, [In] string obj1, [In] object obj2)
    {
      obj0.InfoFormat(obj1, obj2);
    }

    static object \u200D⁯​‏‭‪‌⁮⁯‬‍⁬⁯⁮‎⁭​⁮​⁯⁮‌⁫⁪⁪⁮⁯‏‏⁮‬​‭⁬‭⁭‭‬‌‫‮()
    {
      return new object();
    }
  }
}
