// Decompiled with JetBrains decompiler
// Type: ZoomZoom.CoreObject
// Assembly: ZoomZoom, Version=3.1.2.133, Culture=neutral, PublicKeyToken=null
// MVID: ABEAA923-4AD5-42AE-8951-938AC0FA3F1E
// Assembly location: \\storage-n01.thelaughingman.local\stuff\jaime_temp_DONT_dELETE\jnc8651\ZoomZoom.exe

using log4net;
using Microsoft.Practices.Prism.Events;
using System;
using System.ComponentModel;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using ZoomZoom.Models.Core;
using ZoomZoom.Models.Events;

namespace ZoomZoom
{
  public abstract class CoreObject : ObservableObject
  {
    protected static readonly ILog log = CoreObject.\u200E⁬‭​‫⁪⁯‎⁫‪‫‮⁯⁪‫‍​⁭⁪​⁫‍‌‮⁭‪⁫‬‌‍‎‫‌‭‍‪‪⁮⁫⁫‮(CoreObject.\u202A‎‭‫‫⁮‎⁪‫⁬​⁪⁮‭⁭‭‍‪‭‏⁬⁯⁯⁬‫⁭​⁬⁪‬‮​⁪‪‎‮‪⁯⁬‌‮((MemberInfo) CoreObject.\u206B⁫‬‍⁪‎‮⁯‍‪‪‎‮⁫⁫⁪‬⁮⁭‬‮‌⁮​‪‍‫‎⁯‬⁪‫⁬‏⁫‌‮⁫‎⁯‮()));
    private bool autoGenerated = false;
    protected DateTime _instantiated = DateTime.Now;
    protected Engine engine = (Engine) null;
    protected long uri = 0;
    protected bool isDirty = false;
    protected readonly IEventAggregator _eventAggregator;

    public abstract TraceType TraceType { get; }

    [Browsable(false)]
    [XmlIgnore]
    internal DateTime Instantiated
    {
      get
      {
        DateTime instantiated = this._instantiated;
label_1:
        int num1 = 73289186;
        while (true)
        {
          int num2 = 1987582681;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              num1 = (int) num3 * 876360238 ^ 1177679878;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return instantiated;
      }
    }

    [XmlIgnore]
    [Browsable(false)]
    internal Engine Engine
    {
      get
      {
label_1:
        int num1 = -17079002;
        Engine engine;
        while (true)
        {
          int num2 = -1519467432;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 1:
              num1 = (int) num3 * 1863650651 ^ 1287857639;
              continue;
            case 2:
              engine = this.engine;
              num1 = (int) num3 * 1082769336 ^ -385887971;
              continue;
            case 3:
              goto label_1;
            default:
              goto label_5;
          }
        }
label_5:
        return engine;
      }
      set
      {
label_1:
        int num1 = 639205502;
        while (true)
        {
          int num2 = 1107550956;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              this.engine = value;
              num1 = (int) num3 * 25982106 ^ -1487703643;
              continue;
            case 2:
              goto label_3;
            default:
              goto label_5;
          }
        }
label_5:
        return;
label_3:;
      }
    }

    internal long Uri
    {
      get
      {
        return this.uri;
      }
      set
      {
label_1:
        int num1 = 1068312048;
        while (true)
        {
          int num2 = 958069826;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              goto label_3;
            case 2:
              this.uri = value;
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3068833361U));
              num1 = (int) num3 * 458762239 ^ 1837882675;
              continue;
            default:
              goto label_5;
          }
        }
label_5:
        return;
label_3:;
      }
    }

    internal bool IsDirty
    {
      get
      {
label_1:
        int num1 = 2048142277;
        bool isDirty;
        while (true)
        {
          int num2 = 2130575128;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              isDirty = this.isDirty;
              num1 = (int) num3 * 1269232992 ^ 740207850;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return isDirty;
      }
      set
      {
        this.isDirty = value;
      }
    }

    public bool AutoGenerated
    {
      get
      {
        bool autoGenerated = this.autoGenerated;
label_1:
        int num1 = -76376787;
        while (true)
        {
          int num2 = -1198779796;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 2:
              num1 = (int) num3 * 1661632002 ^ -434208715;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return autoGenerated;
      }
      set
      {
        this.autoGenerated = value;
      }
    }

    public CoreObject()
    {
label_1:
      int num1 = 1869080810;
      while (true)
      {
        int num2 = 1891768500;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 7U)
        {
          case 0:
            goto label_1;
          case 1:
            num1 = (int) num3 * 1664521058 ^ 657584953;
            continue;
          case 2:
            num1 = (int) num3 * -1579093428 ^ 1353767399;
            continue;
          case 3:
            goto label_3;
          case 4:
            this._eventAggregator = ApplicationService.Instance.EventAggregator;
            num1 = (int) num3 * -1058352313 ^ 529667701;
            continue;
          case 5:
            this.Engine = Engine.Instance;
            num1 = (int) num3 * 704987252 ^ -211608079;
            continue;
          case 6:
            num1 = (int) num3 * 568805502 ^ -1646472311;
            continue;
          default:
            goto label_9;
        }
      }
label_9:
      return;
label_3:;
    }

    public override void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
label_1:
      int num1 = -1478781930;
      while (true)
      {
        int num2 = -502164913;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 0:
            goto label_1;
          case 1:
            this.IsDirty = true;
            num1 = (int) num3 * -365702098 ^ -1085615742;
            continue;
          case 3:
            num1 = (int) num3 * -999457122 ^ -52207165;
            continue;
          default:
            goto label_5;
        }
      }
label_5:
      base.RaisePropertyChanged(propertyName);
    }

    protected void Trace(TraceType traceType, string status, params object[] paramList)
    {
label_1:
      int num1 = -1306520160;
      while (true)
      {
        int num2 = -2070355125;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 6U)
        {
          case 0:
            ((CompositePresentationEvent<TraceObject>) this._eventAggregator.GetEvent<TraceEvent>()).Publish(new TraceObject()
            {
              TraceType = traceType,
              Text = status,
              EventTime = DateTime.Now,
              ThrewException = false
            });
            num1 = (int) num3 * -750201267 ^ -286866381;
            continue;
          case 1:
            goto label_3;
          case 2:
            num1 = (int) num3 * 1335349154 ^ -1684165336;
            continue;
          case 3:
            CoreObject.\u200F‎‌​‬‮⁫‭⁮‪‪‮⁪⁫⁬‬⁭⁭⁯‪⁫‎‎‎‎⁮⁫‬‎‬​⁮​‌‏⁪⁭‫‭‮(CoreObject.log, CoreObject.\u202A‮⁪‮⁯‪⁯⁯⁯⁬⁪‬⁬‏‫‭⁪‌⁪‬‮‬⁭‪‮‌⁫‎⁯⁪⁪‌​‭‫⁭‌⁭‪‮(new object[4]
            {
              (object) \u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(3800750532U),
              (object) traceType,
              (object) \u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(4190274489U),
              (object) status
            }), paramList);
            num1 = (int) num3 * -1331529221 ^ 1044696276;
            continue;
          case 4:
            goto label_1;
          case 5:
            int num4 = this.Engine.Settings.IsTracingEnabled(traceType) ? -835173453 : (num4 = -1730407503);
            int num5 = (int) num3 * -1375390477;
            num1 = num4 ^ num5;
            continue;
          default:
            goto label_8;
        }
      }
label_8:
      return;
label_3:;
    }

    protected void TraceError(string status, Exception ex)
    {
label_1:
      int num1 = -554085788;
      while (true)
      {
        int num2 = -153136486;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 1:
            num1 = (int) num3 * -1671039901 ^ -2121156083;
            continue;
          case 2:
            CoreObject.\u200B‍​‌‏⁪⁮⁭⁫‭‫⁭⁬⁬⁮‮‪‏‬‮⁫‏⁭⁪⁫⁮‍⁮‪‮‭‍⁪⁫‏⁫‌⁪⁮‫‮(CoreObject.log, (object) \u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3738210943U), ex);
            num1 = (int) num3 * -1663558649 ^ 971365829;
            continue;
          case 3:
            goto label_1;
          default:
            goto label_5;
        }
      }
label_5:
      this.Engine.RaiseEvent(EngineEvent.Error, ex, false);
    }

    static string \u202A‮⁪‮⁯‪⁯⁯⁯⁬⁪‬⁬‏‫‭⁪‌⁪‬‮‬⁭‪‮‌⁫‎⁯⁪⁪‌​‭‫⁭‌⁭‪‮([In] object[] obj0)
    {
      return string.Concat(obj0);
    }

    static void \u200F‎‌​‬‮⁫‭⁮‪‪‮⁪⁫⁬‬⁭⁭⁯‪⁫‎‎‎‎⁮⁫‬‎‬​⁮​‌‏⁪⁭‫‭‮([In] ILog obj0, [In] string obj1, [In] object[] obj2)
    {
      obj0.DebugFormat(obj1, obj2);
    }

    static void \u200B‍​‌‏⁪⁮⁭⁫‭‫⁭⁬⁬⁮‮‪‏‬‮⁫‏⁭⁪⁫⁮‍⁮‪‮‭‍⁪⁫‏⁫‌⁪⁮‫‮([In] ILog obj0, [In] object obj1, [In] Exception obj2)
    {
      obj0.Error(obj1, obj2);
    }

    static MethodBase \u206B⁫‬‍⁪‎‮⁯‍‪‪‎‮⁫⁫⁪‬⁮⁭‬‮‌⁮​‪‍‫‎⁯‬⁪‫⁬‏⁫‌‮⁫‎⁯‮()
    {
      return MethodBase.GetCurrentMethod();
    }

    static Type \u202A‎‭‫‫⁮‎⁪‫⁬​⁪⁮‭⁭‭‍‪‭‏⁬⁯⁯⁬‫⁭​⁬⁪‬‮​⁪‪‎‮‪⁯⁬‌‮([In] MemberInfo obj0)
    {
      return obj0.DeclaringType;
    }

    static ILog \u200E⁬‭​‫⁪⁯‎⁫‪‫‮⁯⁪‫‍​⁭⁪​⁫‍‌‮⁭‪⁫‬‌‍‎‫‌‭‍‪‪⁮⁫⁫‮([In] Type obj0)
    {
      return LogManager.GetLogger(obj0);
    }
  }
}
