// Decompiled with JetBrains decompiler
// Type: ZoomZoom.LayoutPattern
// Assembly: ZoomZoom, Version=3.1.2.133, Culture=neutral, PublicKeyToken=null
// MVID: ABEAA923-4AD5-42AE-8951-938AC0FA3F1E
// Assembly location: \\storage-n01.thelaughingman.local\stuff\jaime_temp_DONT_dELETE\jnc8651\ZoomZoom.exe

using log4net;
using Microsoft.Practices.Prism.Events;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using System.Xml.Serialization;
using ZoomZoom.Models.Events;
using ZoomZoom.Properties;

namespace ZoomZoom
{
  public class LayoutPattern : CoreObject
  {
    private Engine zoomZoom = (Engine) null;
    private string sourceFile = string.Empty;
    private string primaryMonitor = string.Empty;
    private string secondaryMonitor = string.Empty;
    private ObservableCollection<WindowLayout> windowLayouts = new ObservableCollection<WindowLayout>();
    private bool autogenerated = false;
    private bool dockEngineView = false;
    private WindowEdge dockEdge = WindowEdge.Undefined;
    private ZoomWindowType dockTarget = ZoomWindowType.Meeting;
    private LayoutMode layoutMode = LayoutMode.Undefined;
    private bool stretchingEnabled;
    private string patternName;

    public string PatternName
    {
      get
      {
label_1:
        int num1 = -56787275;
        string patternName;
        while (true)
        {
          int num2 = -1647159204;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              num1 = (int) num3 * -843221990 ^ 196783319;
              continue;
            case 1:
              patternName = this.patternName;
              num1 = (int) num3 * -2085035241 ^ -1420133305;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_5;
          }
        }
label_5:
        return patternName;
      }
      set
      {
label_1:
        int num1 = 1882900999;
        while (true)
        {
          int num2 = 310942220;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              goto label_1;
            case 1:
              goto label_3;
            case 2:
              this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(4231491222U));
              num1 = (int) num3 * 1668099165 ^ 637357291;
              continue;
            case 3:
              this.patternName = value;
              this.SourceFile = string.Empty;
              num1 = (int) num3 * -381552763 ^ -1036775139;
              continue;
            default:
              goto label_6;
          }
        }
label_6:
        return;
label_3:;
      }
    }

    public string PrimaryMonitor
    {
      get
      {
label_1:
        int num1 = 5828150;
        string primaryMonitor;
        while (true)
        {
          int num2 = 370132728;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 1:
              num1 = (int) num3 * 219625441 ^ 1941073665;
              continue;
            case 2:
              primaryMonitor = this.primaryMonitor;
              num1 = (int) num3 * 845501758 ^ -1071011703;
              continue;
            case 3:
              goto label_1;
            default:
              goto label_5;
          }
        }
label_5:
        return primaryMonitor;
      }
      set
      {
        this.primaryMonitor = value;
label_1:
        int num1 = -1653495510;
        while (true)
        {
          int num2 = -827965421;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(3473786203U));
              num1 = (int) num3 * -1032156413 ^ 1925829656;
              continue;
            case 1:
              this.IsDirty = true;
              num1 = (int) num3 * -373206146 ^ 1742694905;
              continue;
            case 2:
              goto label_1;
            case 3:
              goto label_3;
            default:
              goto label_6;
          }
        }
label_6:
        return;
label_3:;
      }
    }

    public string SecondaryMonitor
    {
      get
      {
label_1:
        int num1 = 1235104737;
        string secondaryMonitor;
        while (true)
        {
          int num2 = 1004696259;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              goto label_1;
            case 2:
              secondaryMonitor = this.secondaryMonitor;
              num1 = (int) num3 * 267076816 ^ -1866077920;
              continue;
            case 3:
              num1 = (int) num3 * -1406481776 ^ -1115339810;
              continue;
            default:
              goto label_5;
          }
        }
label_5:
        return secondaryMonitor;
      }
      set
      {
        this.secondaryMonitor = value;
        this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(390501997U));
label_1:
        int num1 = -1494678690;
        while (true)
        {
          int num2 = -1178836581;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              num1 = (int) num3 * -1272118607 ^ -682357138;
              continue;
            case 1:
              num1 = (int) num3 * -1795526212 ^ -188639883;
              continue;
            case 2:
              goto label_1;
            case 3:
              this.IsDirty = true;
              num1 = (int) num3 * 1269565330 ^ 1512775323;
              continue;
            case 4:
              goto label_3;
            default:
              goto label_7;
          }
        }
label_7:
        return;
label_3:;
      }
    }

    public string SourceFile
    {
      get
      {
        bool flag = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(this.sourceFile, string.Empty);
label_1:
        int num1 = -633868778;
        string sourceFile;
        while (true)
        {
          int num2 = -381348067;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 7U)
          {
            case 0:
              goto label_1;
            case 1:
              num1 = (int) num3 * -865223618 ^ -182469136;
              continue;
            case 2:
              this.sourceFile = LayoutPattern.\u206D‎​‪‏‭‫⁮‭⁪⁪‫‫⁭‪‎‎‌⁪‏⁯‍‪⁬‌‏​‬‫‮⁮​⁭⁭‬‍‭⁪‫⁫‮(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(76354748U), (object) this.Engine.Settings.LayoutsRoot, (object) LayoutPattern.\u200E‪‪⁫‏⁫‭‫⁮⁯‏‬‎‌‍‭⁯‎‎⁭‎⁭‌‬‫‬‌‌‬‍‮⁮⁮‫⁭⁭‌‍‎‭‮(this.PatternName, \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(3233217672U), ""));
              num1 = (int) num3 * -856352543 ^ -1078142466;
              continue;
            case 4:
              num1 = (int) num3 * -1282752284 ^ 1775683075;
              continue;
            case 5:
              int num4 = flag ? -1992060545 : (num4 = -1519288683);
              int num5 = (int) num3 * 1412461447;
              num1 = num4 ^ num5;
              continue;
            case 6:
              sourceFile = this.sourceFile;
              num1 = -90083843;
              continue;
            default:
              goto label_8;
          }
        }
label_8:
        return sourceFile;
      }
      set
      {
label_1:
        int num1 = -608862228;
        while (true)
        {
          int num2 = -1578752309;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 6U)
          {
            case 0:
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(2621035174U));
              num1 = (int) num3 * 455943759 ^ 125988768;
              continue;
            case 1:
              goto label_3;
            case 2:
              num1 = (int) num3 * 864763172 ^ -897009566;
              continue;
            case 3:
              this.sourceFile = value;
              num1 = (int) num3 * 970136436 ^ -1553280479;
              continue;
            case 4:
              goto label_1;
            case 5:
              this.IsDirty = true;
              num1 = (int) num3 * 173951944 ^ 768855277;
              continue;
            default:
              goto label_8;
          }
        }
label_8:
        return;
label_3:;
      }
    }

    public bool StretchingEnabled
    {
      get
      {
        return this.stretchingEnabled;
      }
      set
      {
        this.stretchingEnabled = value;
label_1:
        int num1 = 119662516;
        while (true)
        {
          int num2 = 1024616383;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              goto label_1;
            case 1:
              num1 = (int) num3 * 568468132 ^ -132437207;
              continue;
            case 2:
              this.IsDirty = true;
              num1 = (int) num3 * -764121156 ^ 1793222302;
              continue;
            case 3:
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(3726854058U));
              num1 = (int) num3 * -613170830 ^ -1940063621;
              continue;
            case 4:
              goto label_3;
            default:
              goto label_7;
          }
        }
label_7:
        return;
label_3:;
      }
    }

    public bool DockEngineView
    {
      get
      {
        bool dockEngineView = this.dockEngineView;
label_1:
        int num1 = 1397957655;
        while (true)
        {
          int num2 = 655316438;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * -231034503 ^ 180646953;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return dockEngineView;
      }
      set
      {
        this.dockEngineView = value;
        this.RaisePropertyChanged(\u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(1090615088U));
      }
    }

    public override TraceType TraceType
    {
      get
      {
        TraceType traceType = TraceType.Layout;
label_1:
        int num1 = -1375480525;
        while (true)
        {
          int num2 = -541501059;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * -346821276 ^ -2040339075;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return traceType;
      }
    }

    public ObservableCollection<WindowLayout> WindowLayouts
    {
      get
      {
        ObservableCollection<WindowLayout> windowLayouts = this.windowLayouts;
label_1:
        int num1 = 547221246;
        while (true)
        {
          int num2 = 47013263;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 1:
              num1 = (int) num3 * 150000319 ^ -1759196447;
              continue;
            case 2:
              goto label_1;
            default:
              goto label_4;
          }
        }
label_4:
        return windowLayouts;
      }
      private set
      {
        this.windowLayouts = value;
        this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(2170765524U));
      }
    }

    public ZoomWindowType DockTarget
    {
      get
      {
label_1:
        int num1 = -387505923;
        ZoomWindowType dockTarget;
        while (true)
        {
          int num2 = -925004956;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 1:
              dockTarget = this.dockTarget;
              num1 = (int) num3 * 1762194315 ^ -761782480;
              continue;
            case 2:
              goto label_1;
            case 3:
              num1 = (int) num3 * 685745342 ^ 1057215326;
              continue;
            default:
              goto label_5;
          }
        }
label_5:
        return dockTarget;
      }
      set
      {
        this.dockTarget = value;
        this.RaisePropertyChanged(\u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(1527673805U));
      }
    }

    public WindowEdge DockEdge
    {
      get
      {
        WindowEdge dockEdge = this.dockEdge;
label_1:
        int num1 = 1180428459;
        while (true)
        {
          int num2 = 192509147;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              num1 = (int) num3 * 1889164162 ^ -1446642915;
              continue;
            default:
              goto label_4;
          }
        }
label_4:
        return dockEdge;
      }
      set
      {
label_1:
        int num1 = 2129513842;
        while (true)
        {
          int num2 = 896322174;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_1;
            case 1:
              this.dockEdge = value;
              this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(4241001169U));
              num1 = (int) num3 * 560462445 ^ -1925875271;
              continue;
            case 2:
              goto label_3;
            default:
              goto label_5;
          }
        }
label_5:
        return;
label_3:;
      }
    }

    public LayoutMode LayoutMode
    {
      get
      {
        return this.layoutMode;
      }
      set
      {
label_1:
        int num1 = 307978671;
        while (true)
        {
          int num2 = 1735474792;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              goto label_1;
            case 1:
              this.RaisePropertyChanged(\u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(28405143U));
              num1 = (int) num3 * 2059416040 ^ 996550335;
              continue;
            case 2:
              goto label_3;
            case 3:
              this.layoutMode = value;
              num1 = (int) num3 * -1776589203 ^ 620867712;
              continue;
            case 4:
              num1 = (int) num3 * -860777501 ^ -997800676;
              continue;
            default:
              goto label_7;
          }
        }
label_7:
        return;
label_3:;
      }
    }

    public LayoutPattern()
    {
label_1:
      int num1 = 171792950;
      while (true)
      {
        int num2 = 2022058007;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 0:
            goto label_3;
          case 1:
            num1 = (int) num3 * -1105032379 ^ 1652477136;
            continue;
          case 2:
            this.zoomZoom = Engine.Instance;
            num1 = (int) num3 * 885994670 ^ -1033734201;
            continue;
          case 3:
            goto label_1;
          default:
            goto label_6;
        }
      }
label_6:
      return;
label_3:;
    }

    public LayoutPattern(LayoutPattern source)
    {
label_1:
      int num1 = 1912450731;
      while (true)
      {
        int num2 = 463887791;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 11U)
        {
          case 0:
            goto label_1;
          case 1:
            num1 = (int) num3 * 603074458 ^ 1849005788;
            continue;
          case 2:
            num1 = (int) num3 * -1795067517 ^ -1943919273;
            continue;
          case 3:
            num1 = (int) num3 * -1347522983 ^ 1873254224;
            continue;
          case 4:
            this.zoomZoom = Engine.Instance;
            num1 = (int) num3 * -622014142 ^ 766058946;
            continue;
          case 5:
            num1 = (int) num3 * 2040197711 ^ -957618589;
            continue;
          case 6:
            this.PatternName = LayoutPattern.\u202D‮⁫⁯⁬‏‌⁭⁬⁮‏⁫‭⁪‏⁫‭‌​‏‫⁪‫‪‮‪​​‭‪‍‮‏‬‭‌‌⁯⁬‫‮(source.PatternName, \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(2978894311U));
            num1 = (int) num3 * -2073285050 ^ -69192513;
            continue;
          case 8:
            this.PrimaryMonitor = source.PrimaryMonitor;
            num1 = (int) num3 * 1161574527 ^ -2035038221;
            continue;
          case 9:
            num1 = (int) num3 * -1825976574 ^ -1252926652;
            continue;
          case 10:
            this.SecondaryMonitor = source.SecondaryMonitor;
            num1 = (int) num3 * -86745487 ^ 2030762297;
            continue;
          default:
            goto label_12;
        }
      }
label_12:
      IEnumerator<WindowLayout> enumerator = ((Collection<WindowLayout>) source.WindowLayouts).GetEnumerator();
      try
      {
        while (LayoutPattern.\u206F‬‍‭‬⁬⁮⁪⁯⁬‌‫‫‮‭⁭⁬⁫‭‌⁮⁯⁪⁫‍‮‎‬⁭⁪‌‌‪⁫⁭⁭‭‎‫‬‮((IEnumerator) enumerator))
        {
          WindowLayout windowLayout = new WindowLayout(enumerator.Current, this);
          windowLayout.PropertyChanged += new PropertyChangedEventHandler(this.WindowLayout_PropertyChanged);
          ((Collection<WindowLayout>) this.WindowLayouts).Add(windowLayout);
        }
      }
      finally
      {
        if (enumerator != null)
          LayoutPattern.\u200F‪⁯⁫‬‎⁯‭‮‬⁬⁯‬‍‍‏‫⁭‬​‮‏‮‫‮‬⁭⁯‬⁬⁯‭​‮⁪‏‎⁬⁭⁭‮((IDisposable) enumerator);
      }
      this.AutoGenerated = false;
      this.SourceFile = string.Empty;
      this.IsDirty = true;
      this.StretchingEnabled = source.StretchingEnabled;
    }

    internal void Delete(string alternatePath = "")
    {
      try
      {
        string str = this.SourceFile;
        bool flag = !LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(alternatePath, string.Empty);
label_2:
        int num1 = 1691341533;
        while (true)
        {
          int num2 = 1171935633;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              str = alternatePath;
              num1 = (int) num3 * 1634515444 ^ -580564190;
              continue;
            case 1:
              int num4 = flag ? -1110547655 : (num4 = -1026664954);
              int num5 = (int) num3 * 1593243330;
              num1 = num4 ^ num5;
              continue;
            case 3:
              num1 = (int) num3 * 54584396 ^ -78819766;
              continue;
            case 4:
              goto label_2;
            default:
              goto label_7;
          }
        }
label_7:
        try
        {
label_9:
          int num2 = 1957611823;
          while (true)
          {
            int num3 = 1171935633;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 4U)
            {
              case 0:
                goto label_28;
              case 1:
                num2 = (int) num4 * 2100625981 ^ -1245089612;
                continue;
              case 2:
                LayoutPattern.\u200D‍‍⁮‮‪⁬‬‬‎⁮⁮‏‌‍‬​⁫⁫⁪‫⁯‭⁭‍⁪‌‌‮​⁭‏‮⁬‍‌⁮‫⁯‫‮(str);
                num2 = (int) num4 * -491581306 ^ -251492596;
                continue;
              case 3:
                goto label_9;
              default:
                goto label_25;
            }
          }
label_25:
          return;
label_28:;
        }
        catch (Exception ex)
        {
label_15:
          int num2 = 1024175839;
          while (true)
          {
            int num3 = 1171935633;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 4U)
            {
              case 0:
                goto label_15;
              case 1:
                num2 = (int) num4 * -909189993 ^ -676623287;
                continue;
              case 2:
                num2 = (int) num4 * -1299807846 ^ 1352906856;
                continue;
              case 3:
                goto label_21;
              default:
                goto label_20;
            }
          }
label_20:
          return;
label_21:;
        }
      }
      catch (Exception ex)
      {
label_23:
        int num1 = 1160904091;
        while (true)
        {
          int num2 = 1171935633;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 4U)
          {
            case 0:
              goto label_23;
            case 1:
              LayoutPattern.\u202C‭‬‮⁮⁫‫‮‫‪‪⁫‏‍⁫‫‭⁫‍⁫⁮⁫‫⁭‌‮⁭‏‌⁭‍‍⁬‪‫⁪​‬⁪⁫‮(CoreObject.log, (object) ex);
              num1 = (int) num3 * -1181248232 ^ -1392289470;
              continue;
            case 2:
              num1 = (int) num3 * -815506152 ^ -1341494300;
              continue;
            case 3:
              goto label_17;
            default:
              goto label_13;
          }
        }
label_13:
        return;
label_17:;
      }
    }

    public override string ToString()
    {
      string patternName = this.PatternName;
label_1:
      int num1 = -252987045;
      while (true)
      {
        int num2 = -672653088;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 0:
            goto label_1;
          case 1:
            num1 = (int) num3 * 1196327985 ^ -663002330;
            continue;
          default:
            goto label_4;
        }
      }
label_4:
      return patternName;
    }

    public override bool Equals(object obj)
    {
label_1:
      int num1 = 1124601547;
      bool flag1;
      while (true)
      {
        int num2 = 133749052;
        uint num3;
        bool flag2;
        LayoutPattern layoutPattern;
        switch ((num3 = (uint) (num1 ^ num2)) % 8U)
        {
          case 0:
            num1 = (int) num3 * 1632833333 ^ -1576812519;
            continue;
          case 1:
            int num4 = !flag2 ? 340307284 : (num4 = 1806870626);
            int num5 = (int) num3 * -7864442;
            num1 = num4 ^ num5;
            continue;
          case 2:
            goto label_1;
          case 4:
            flag2 = layoutPattern != null;
            num1 = (int) num3 * -1038908216 ^ -569882835;
            continue;
          case 5:
            bool flag3 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(layoutPattern.PatternName, this.PatternName);
            flag1 = this.\u202B⁪⁯⁪⁮‮‮⁮‍⁭‮‍⁬⁬‎‬‮⁮⁮⁮⁪⁫‪‍⁪⁯‬​⁪⁬‎⁪‪‍⁪⁯⁭‫‪‬‮(obj) & flag3;
            num1 = (int) num3 * 1280835102 ^ 1775166393;
            continue;
          case 6:
            flag1 = this.\u202B⁪⁯⁪⁮‮‮⁮‍⁭‮‍⁬⁬‎‬‮⁮⁮⁮⁪⁫‪‍⁪⁯‬​⁪⁬‎⁪‪‍⁪⁯⁭‫‪‬‮(obj);
            num1 = 1204231967;
            continue;
          case 7:
            layoutPattern = obj as LayoutPattern;
            num1 = (int) num3 * -1278917834 ^ 1278533714;
            continue;
          default:
            goto label_9;
        }
      }
label_9:
      return flag1;
    }

    public override int GetHashCode()
    {
label_1:
      int num1 = 842286006;
      int num2;
      while (true)
      {
        int num3 = 2135364479;
        uint num4;
        bool flag;
        switch ((num4 = (uint) (num1 ^ num3)) % 8U)
        {
          case 0:
            num2 = this.\u206F‫⁪‭​‎‫‫‏⁬‌⁯‪⁪‫‭‭‏‭⁬‍⁬⁬‍‍​⁫‏‫⁭‪‮​⁫‫‍‍​‎‎‮();
            num1 = 1834905836;
            continue;
          case 1:
            flag = !LayoutPattern.\u200E‮‮‫⁫‌‮⁬​‬​​‫‌⁪‭​⁭‫⁯‎‪‍‪‎‎⁫⁮⁪‮‏​‍⁯⁯‎​‌⁫‮(this.PatternName);
            num1 = (int) num4 * -1233983905 ^ 264330586;
            continue;
          case 2:
            int num5 = !flag ? -700173631 : (num5 = -1853449);
            int num6 = (int) num4 * -60513277;
            num1 = num5 ^ num6;
            continue;
          case 3:
            num1 = (int) num4 * 84200779 ^ 82087906;
            continue;
          case 5:
            num2 = LayoutPattern.\u206B‎⁫⁭⁬‍‭⁪⁯⁪‌⁫‍‫⁪⁯⁮‍​‪‬‪‍‫‬⁯‏‫⁮⁮​⁭⁬‍‌⁪⁬‎⁮‎‮((object) this.PatternName);
            num1 = (int) num4 * 924933212 ^ 398223231;
            continue;
          case 6:
            num1 = (int) num4 * -1740349970 ^ -426231410;
            continue;
          case 7:
            goto label_1;
          default:
            goto label_9;
        }
      }
label_9:
      return num2;
    }

    private void WindowLayout_PropertyChanged(object sender, PropertyChangedEventArgs e)
    {
label_1:
      int num1 = 1538384998;
      while (true)
      {
        int num2 = 1444094634;
        uint num3;
        switch ((num3 = (uint) (num1 ^ num2)) % 3U)
        {
          case 1:
            this.IsDirty = true;
            num1 = (int) num3 * -1716742382 ^ 1772789807;
            continue;
          case 2:
            goto label_1;
          default:
            goto label_4;
        }
      }
label_4:
      this.RaisePropertyChanged(\u003CModule\u003E.\u202A​‬⁪‫‪‫‪⁯⁭⁮‮⁭‪‫⁪⁮⁫‎⁫⁭⁮‭‪⁫‏‮‎‭‍‌⁮‎‫‍​⁮⁮‎‎‮<string>(2207409321U));
    }

    public WindowLayout AddWindowLayout(ZoomWindowType zoomWindowType, string deviceName, int x, int y, int width, int height)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      LayoutPattern.\u003C\u003Ec__DisplayClass39_0 cDisplayClass390 = new LayoutPattern.\u003C\u003Ec__DisplayClass39_0();
label_1:
      int num1 = -1982553200;
      WindowLayout windowLayout1;
      while (true)
      {
        int num2 = -1216605292;
        uint num3;
        WindowLayout windowLayout2;
        bool flag;
        switch ((num3 = (uint) (num1 ^ num2)) % 18U)
        {
          case 0:
            num1 = (int) num3 * -1959984110 ^ 1737213848;
            continue;
          case 1:
            num1 = (int) num3 * 684667879 ^ 1971134718;
            continue;
          case 2:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass390.zoomWindowType = zoomWindowType;
            num1 = (int) num3 * 1765183134 ^ -327305746;
            continue;
          case 3:
            goto label_1;
          case 4:
            windowLayout2.Stretch = ScreenStretching.Undefined;
            windowLayout1 = windowLayout2;
            num1 = (int) num3 * -1176359002 ^ -1108597659;
            continue;
          case 5:
            windowLayout2.WindowType = WindowType.Interface;
            num1 = (int) num3 * 700106438 ^ 375239961;
            continue;
          case 6:
            // ISSUE: method pointer
            windowLayout2 = (WindowLayout) Enumerable.FirstOrDefault<WindowLayout>((IEnumerable<M0>) this.WindowLayouts, (Func<M0, bool>) new Func<WindowLayout, bool>((object) cDisplayClass390, __methodptr(\u003CAddWindowLayout\u003Eb__0)));
            flag = windowLayout2 == null;
            num1 = (int) num3 * -1185176933 ^ 479064760;
            continue;
          case 7:
            windowLayout2.Y = y;
            windowLayout2.Width = width;
            num1 = (int) num3 * -1136185087 ^ 1852983642;
            continue;
          case 8:
            int num4 = !flag ? 611358031 : (num4 = 1019743376);
            int num5 = (int) num3 * 930293510;
            num1 = num4 ^ num5;
            continue;
          case 9:
            // ISSUE: reference to a compiler-generated field
            windowLayout2.ZoomWindowType = cDisplayClass390.zoomWindowType;
            windowLayout2.Monitor = deviceName;
            num1 = (int) num3 * -621349169 ^ 1762890525;
            continue;
          case 11:
            windowLayout2.Hidden = false;
            windowLayout2.X = x;
            num1 = -524550256;
            continue;
          case 12:
            windowLayout2 = new WindowLayout(this);
            windowLayout2.PropertyChanged += new PropertyChangedEventHandler(this.WindowLayout_PropertyChanged);
            ((Collection<WindowLayout>) this.WindowLayouts).Add(windowLayout2);
            num1 = (int) num3 * -1971768689 ^ 1571243867;
            continue;
          case 13:
            windowLayout2.WindowVisibility = WindowVisibility.Show;
            num1 = (int) num3 * 1549334064 ^ 533047038;
            continue;
          case 14:
            num1 = (int) num3 * -795628739 ^ -2052013431;
            continue;
          case 15:
            num1 = (int) num3 * 2135270934 ^ 200728766;
            continue;
          case 16:
            num1 = (int) num3 * -1792446600 ^ 1233216973;
            continue;
          case 17:
            windowLayout2.Height = height;
            num1 = (int) num3 * 1278865891 ^ -961214636;
            continue;
          default:
            goto label_19;
        }
      }
label_19:
      return windowLayout1;
    }

    public WindowLayout AddWindowLayout(ZoomWindowType zoomWindowType, string deviceName, ScreenPlacement horizontal, ScreenPlacement vertical, ScreenStretching stretch = ScreenStretching.Undefined)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      LayoutPattern.\u003C\u003Ec__DisplayClass40_0 cDisplayClass400 = new LayoutPattern.\u003C\u003Ec__DisplayClass40_0();
label_1:
      int num1 = -1491464146;
      WindowLayout windowLayout1;
      while (true)
      {
        int num2 = -1563037030;
        uint num3;
        WindowLayout windowLayout2;
        bool flag;
        switch ((num3 = (uint) (num1 ^ num2)) % 20U)
        {
          case 0:
            num1 = (int) num3 * -898784346 ^ 1082426607;
            continue;
          case 1:
            num1 = (int) num3 * 802175978 ^ -1041622283;
            continue;
          case 2:
            goto label_1;
          case 3:
            windowLayout2.Stretch = stretch;
            num1 = (int) num3 * 1598140384 ^ 839302077;
            continue;
          case 4:
            // ISSUE: reference to a compiler-generated field
            windowLayout2.ZoomWindowType = cDisplayClass400.zoomWindowType;
            num1 = (int) num3 * -482170400 ^ -938990780;
            continue;
          case 5:
            windowLayout2.Horizontal = horizontal;
            windowLayout2.WindowType = WindowType.Interface;
            num1 = (int) num3 * 412824774 ^ -882137072;
            continue;
          case 6:
            windowLayout2 = new WindowLayout(this);
            windowLayout2.PropertyChanged += new PropertyChangedEventHandler(this.WindowLayout_PropertyChanged);
            num1 = (int) num3 * -742671334 ^ -2121772820;
            continue;
          case 7:
            num1 = (int) num3 * -490208362 ^ -1298690958;
            continue;
          case 8:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass400.zoomWindowType = zoomWindowType;
            num1 = (int) num3 * 234964486 ^ 652575655;
            continue;
          case 9:
            windowLayout2.Monitor = deviceName;
            num1 = (int) num3 * -1877236597 ^ -2000550679;
            continue;
          case 10:
            int num4 = flag ? 1825181763 : (num4 = 2076878533);
            int num5 = (int) num3 * 1349676985;
            num1 = num4 ^ num5;
            continue;
          case 11:
            windowLayout1 = windowLayout2;
            num1 = (int) num3 * -1724615213 ^ -1342308920;
            continue;
          case 12:
            num1 = (int) num3 * 940454650 ^ 1203302275;
            continue;
          case 13:
            // ISSUE: method pointer
            windowLayout2 = (WindowLayout) Enumerable.FirstOrDefault<WindowLayout>((IEnumerable<M0>) this.WindowLayouts, (Func<M0, bool>) new Func<WindowLayout, bool>((object) cDisplayClass400, __methodptr(\u003CAddWindowLayout\u003Eb__0)));
            flag = windowLayout2 == null;
            num1 = (int) num3 * -626754766 ^ 882724714;
            continue;
          case 14:
            ((Collection<WindowLayout>) this.WindowLayouts).Add(windowLayout2);
            num1 = (int) num3 * -1266642528 ^ 1301809070;
            continue;
          case 16:
            num1 = (int) num3 * 1564449697 ^ -715366039;
            continue;
          case 17:
            windowLayout2.Hidden = false;
            windowLayout2.Vertical = vertical;
            num1 = -710307050;
            continue;
          case 18:
            num1 = (int) num3 * 606610081 ^ -2097985631;
            continue;
          case 19:
            windowLayout2.WindowVisibility = WindowVisibility.Show;
            num1 = (int) num3 * 1905319752 ^ -231001175;
            continue;
          default:
            goto label_21;
        }
      }
label_21:
      return windowLayout1;
    }

    public WindowLayout AddWindowLayout(ZoomWindowType zoomWindowType, WindowVisibility visibility)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      LayoutPattern.\u003C\u003Ec__DisplayClass41_0 cDisplayClass410 = new LayoutPattern.\u003C\u003Ec__DisplayClass41_0();
label_1:
      int num1 = -1531625064;
      WindowLayout windowLayout1;
      while (true)
      {
        int num2 = -1125570245;
        uint num3;
        WindowLayout windowLayout2;
        bool flag1;
        bool flag2;
        int num4;
        switch ((num3 = (uint) (num1 ^ num2)) % 17U)
        {
          case 0:
            windowLayout2.Hidden = flag1;
            num1 = -1546416445;
            continue;
          case 1:
            num1 = (int) num3 * -2089629218 ^ 1616908075;
            continue;
          case 3:
            num1 = (int) num3 * 1675705548 ^ 691495560;
            continue;
          case 4:
            flag2 = windowLayout2 == null;
            num1 = (int) num3 * -570097439 ^ -1691998304;
            continue;
          case 5:
            if (visibility == WindowVisibility.Hide)
            {
              num4 = 1;
              break;
            }
            num1 = (int) num3 * -701436363 ^ -861464867;
            continue;
          case 6:
            windowLayout2 = new WindowLayout(this);
            num1 = (int) num3 * 1428891669 ^ 470465159;
            continue;
          case 7:
            num4 = 0;
            break;
          case 8:
            num1 = (int) num3 * -814470806 ^ 961302882;
            continue;
          case 9:
            // ISSUE: reference to a compiler-generated field
            cDisplayClass410.zoomWindowType = zoomWindowType;
            num1 = (int) num3 * -652595501 ^ -171799133;
            continue;
          case 10:
            goto label_1;
          case 11:
            // ISSUE: reference to a compiler-generated field
            windowLayout2.ZoomWindowType = cDisplayClass410.zoomWindowType;
            num1 = (int) num3 * 1803500630 ^ -1650378881;
            continue;
          case 12:
            ((Collection<WindowLayout>) this.WindowLayouts).Add(windowLayout2);
            num1 = (int) num3 * 547273492 ^ 1662623852;
            continue;
          case 13:
            // ISSUE: method pointer
            windowLayout2 = (WindowLayout) Enumerable.FirstOrDefault<WindowLayout>((IEnumerable<M0>) this.WindowLayouts, (Func<M0, bool>) new Func<WindowLayout, bool>((object) cDisplayClass410, __methodptr(\u003CAddWindowLayout\u003Eb__0)));
            num1 = (int) num3 * -675380255 ^ -57337095;
            continue;
          case 14:
            int num5 = !flag2 ? -1231999050 : (num5 = -644474282);
            int num6 = (int) num3 * 1975815525;
            num1 = num5 ^ num6;
            continue;
          case 15:
            windowLayout2.PropertyChanged += new PropertyChangedEventHandler(this.WindowLayout_PropertyChanged);
            num1 = (int) num3 * 1222198957 ^ -584951892;
            continue;
          case 16:
            windowLayout2.WindowVisibility = visibility;
            windowLayout1 = windowLayout2;
            num1 = (int) num3 * -1303685539 ^ -1088813526;
            continue;
          default:
            goto label_21;
        }
        flag1 = num4 != 0;
        num1 = -1604908320;
      }
label_21:
      return windowLayout1;
    }

    internal void RemoveWindowLayout(WindowLayout layout)
    {
      try
      {
label_2:
        int num1 = -1184568809;
        while (true)
        {
          int num2 = -1011071685;
          uint num3;
          bool flag;
          switch ((num3 = (uint) (num1 ^ num2)) % 9U)
          {
            case 0:
              goto label_18;
            case 1:
              flag = ((Collection<WindowLayout>) this.WindowLayouts).Contains(layout);
              num1 = (int) num3 * 953888859 ^ 777078153;
              continue;
            case 2:
              layout.PropertyChanged -= new PropertyChangedEventHandler(this.WindowLayout_PropertyChanged);
              num1 = (int) num3 * -948867471 ^ 1136345996;
              continue;
            case 3:
              this.RaisePropertyChanged(\u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(2170765524U));
              num1 = -1876857638;
              continue;
            case 4:
              goto label_2;
            case 5:
              layout = (WindowLayout) null;
              num1 = (int) num3 * 1687494745 ^ 1607526284;
              continue;
            case 6:
              int num4 = !flag ? 660059917 : (num4 = 2005511322);
              int num5 = (int) num3 * -2084052083;
              num1 = num4 ^ num5;
              continue;
            case 7:
              num1 = (int) num3 * 399413116 ^ 597488621;
              continue;
            case 8:
              ((Collection<WindowLayout>) this.WindowLayouts).Remove(layout);
              num1 = (int) num3 * -1863760388 ^ 1103704170;
              continue;
            default:
              goto label_16;
          }
        }
label_16:
        return;
label_18:;
      }
      catch (Exception ex)
      {
label_14:
        int num1 = -84910268;
        while (true)
        {
          int num2 = -1011071685;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 3U)
          {
            case 0:
              goto label_14;
            case 1:
              LayoutPattern.\u202C‭‬‮⁮⁫‫‮‫‪‪⁫‏‍⁫‫‭⁫‍⁫⁮⁫‫⁭‌‮⁭‏‌⁭‍‍⁬‪‫⁪​‬⁪⁫‮(CoreObject.log, (object) ex);
              num1 = (int) num3 * 1875028432 ^ 1911652861;
              continue;
            case 2:
              goto label_12;
            default:
              goto label_4;
          }
        }
label_4:
        return;
label_12:;
      }
    }

    public static LayoutPattern LoadPattern(string fileName)
    {
      LayoutPattern layoutPattern1 = (LayoutPattern) null;
label_1:
      int num1 = 932758192;
      bool flag1;
      while (true)
      {
        int num2 = 563942489;
        uint num3;
        bool flag2;
        switch ((num3 = (uint) (num1 ^ num2)) % 4U)
        {
          case 0:
            if (flag2)
            {
              num1 = (int) num3 * 246884118 ^ -577040213;
              continue;
            }
            goto label_57;
          case 1:
            flag1 = false;
            flag2 = LayoutPattern.\u202A‬‎⁯‬​⁬‎⁭‎⁮‌⁬‫⁫‌‬‮‍‌⁭‭⁭⁪⁪‪​‎‪⁯‫⁭‪‮‏‍‍‪⁭⁯‮(fileName);
            num1 = (int) num3 * 879542500 ^ -1148979791;
            continue;
          case 3:
            goto label_1;
          default:
            goto label_6;
        }
      }
label_6:
      try
      {
label_8:
        int num2 = 1490424625;
        while (true)
        {
          int num3 = 563942489;
          uint num4;
          XmlSerializer xmlSerializer;
          TextReader textReader;
          switch ((num4 = (uint) (num2 ^ num3)) % 10U)
          {
            case 1:
              textReader = (TextReader) LayoutPattern.\u202A‫‫‬‌‍‫‍‬⁮‌⁭‎⁯‍‍‭‌⁪‭‫‌‎‎⁭‎‪‌‏⁮‎‮⁯⁬⁭‭‍‌‍⁬‮(fileName);
              num2 = (int) num4 * 1061755367 ^ -993203999;
              continue;
            case 2:
              // ISSUE: type reference
              xmlSerializer = LayoutPattern.\u202D⁭‮‎‍⁮⁪‏‎‪⁭‏⁭​‍‎‫‪‮‮⁬‬⁭‬‏​‌‫⁯‌⁮‮‬⁮‪⁫‫‏‫‌‮(LayoutPattern.\u202A‎‎‌‬‏‭⁭‍⁯‎⁭‬⁬‎‮‬‍⁭‭‭⁬⁪‬​⁭‎‏‪‎‮‫‍​‭‮‫‭‮⁮‮(__typeref (LayoutPattern)));
              num2 = (int) num4 * -1693364517 ^ 51598138;
              continue;
            case 3:
              layoutPattern1 = (LayoutPattern) LayoutPattern.\u202E​⁯⁮‎‌‮‌‬‬‎⁬‍‏⁪⁭⁯⁯⁬‎⁯‍‪⁪⁫‪‌​‭​‮⁭‫⁯⁭⁭⁮⁪‪‫‮(xmlSerializer, textReader);
              num2 = (int) num4 * 1784303678 ^ 1088108429;
              continue;
            case 4:
              num2 = (int) num4 * 871947952 ^ -642555216;
              continue;
            case 5:
              num2 = (int) num4 * 861816903 ^ -1985767854;
              continue;
            case 6:
              layoutPattern1.SourceFile = fileName;
              num2 = (int) num4 * -408823583 ^ 1132297617;
              continue;
            case 7:
              LayoutPattern.\u206A‎‭‫‮‫​‫‫‍​‍​⁬⁭⁯⁭⁬‭⁫‫⁬⁫⁯‬‍‭‮⁯‌⁭‫⁬‍⁯⁪⁯⁪‬⁮‮(textReader);
              num2 = (int) num4 * 1782876244 ^ -1934391468;
              continue;
            case 8:
              textReader = (TextReader) null;
              xmlSerializer = (XmlSerializer) null;
              num2 = (int) num4 * 1445097140 ^ -1783111621;
              continue;
            case 9:
              goto label_8;
            default:
              goto label_18;
          }
        }
label_18:
        IEnumerator<WindowLayout> enumerator = ((Collection<WindowLayout>) layoutPattern1.WindowLayouts).GetEnumerator();
        try
        {
label_25:
          int num3 = !LayoutPattern.\u206F‬‍‭‬⁬⁮⁪⁯⁬‌‫‫‮‭⁭⁬⁫‭‌⁮⁯⁪⁫‍‮‎‬⁭⁪‌‌‪⁫⁭⁭‭‎‫‬‮((IEnumerator) enumerator) ? 1020734741 : (num3 = 70790531);
          while (true)
          {
            int num4 = 563942489;
            uint num5;
            WindowLayout current;
            switch ((num5 = (uint) (num3 ^ num4)) % 7U)
            {
              case 0:
                num3 = (int) num5 * -258057909 ^ -747024213;
                continue;
              case 1:
                current = enumerator.Current;
                num3 = 5452413;
                continue;
              case 2:
                goto label_25;
              case 3:
                current.Pattern = layoutPattern1;
                num3 = (int) num5 * -365277016 ^ 129239917;
                continue;
              case 4:
                current.PropertyChanged += new PropertyChangedEventHandler(layoutPattern1.WindowLayout_PropertyChanged);
                num3 = (int) num5 * 1057402938 ^ 809016813;
                continue;
              case 6:
                num3 = 70790531;
                continue;
              default:
                goto label_33;
            }
          }
        }
        finally
        {
          if (enumerator != null)
          {
label_28:
            int num3 = 691449914;
            while (true)
            {
              int num4 = 563942489;
              uint num5;
              switch ((num5 = (uint) (num3 ^ num4)) % 4U)
              {
                case 0:
                  goto label_28;
                case 2:
                  num3 = (int) num5 * 1095642026 ^ 693187136;
                  continue;
                case 3:
                  LayoutPattern.\u200F‪⁯⁫‬‎⁯‭‮‬⁬⁯‬‍‍‏‫⁭‬​‮‏‮‫‮‬⁭⁯‬⁬⁯‭​‮⁪‏‎⁬⁭⁭‮((IDisposable) enumerator);
                  num3 = (int) num5 * 2098247602 ^ 1116812757;
                  continue;
                default:
                  goto label_32;
              }
            }
          }
label_32:;
        }
label_33:
        layoutPattern1.IsDirty = false;
      }
      catch (Exception ex)
      {
label_35:
        int num2 = 22510016;
        while (true)
        {
          int num3 = 563942489;
          uint num4;
          switch ((num4 = (uint) (num2 ^ num3)) % 4U)
          {
            case 0:
              flag1 = true;
              num2 = (int) num4 * 641818876 ^ -141817538;
              continue;
            case 1:
              LayoutPattern.\u202C‭‬‮⁮⁫‫‮‫‪‪⁫‏‍⁫‫‭⁫‍⁫⁮⁫‫⁭‌‮⁭‏‌⁭‍‍⁬‪‫⁪​‬⁪⁫‮(CoreObject.log, (object) ex);
              num2 = (int) num4 * 1989075955 ^ -1911110546;
              continue;
            case 2:
              goto label_35;
            default:
              goto label_39;
          }
        }
      }
label_39:
      bool flag3 = flag1;
label_40:
      int num6 = 1278899946;
      while (true)
      {
        int num2 = 563942489;
        uint num3;
        switch ((num3 = (uint) (num6 ^ num2)) % 3U)
        {
          case 0:
            goto label_40;
          case 1:
            if (flag3)
            {
              num6 = (int) num3 * 480335942 ^ 1763112313;
              continue;
            }
            goto label_58;
          default:
            goto label_44;
        }
      }
label_44:
      try
      {
label_46:
        int num2 = 859011393;
        while (true)
        {
          int num3 = 563942489;
          uint num4;
          switch ((num4 = (uint) (num2 ^ num3)) % 3U)
          {
            case 1:
              LayoutPattern.\u200D‍‍⁮‮‪⁬‬‬‎⁮⁮‏‌‍‬​⁫⁫⁪‫⁯‭⁭‍⁪‌‌‮​⁭‏‮⁬‍‌⁮‫⁯‫‮(fileName);
              num2 = (int) num4 * 1104085186 ^ 1257758239;
              continue;
            case 2:
              goto label_46;
            default:
              goto label_53;
          }
        }
      }
      catch (Exception ex)
      {
label_50:
        int num2 = 1370060994;
        while (true)
        {
          int num3 = 563942489;
          uint num4;
          switch ((num4 = (uint) (num2 ^ num3)) % 3U)
          {
            case 1:
              num2 = (int) num4 * 464931927 ^ 1211791367;
              continue;
            case 2:
              goto label_50;
            default:
              goto label_53;
          }
        }
      }
label_53:
label_54:
      int num7 = 1028451430;
label_55:
      while (true)
      {
        int num2 = 563942489;
        uint num3;
        switch ((num3 = (uint) (num7 ^ num2)) % 5U)
        {
          case 0:
            goto label_54;
          case 1:
            goto label_57;
          case 2:
            num7 = (int) num3 * -18104926 ^ 1750062410;
            continue;
          case 3:
            goto label_58;
          default:
            goto label_59;
        }
      }
label_59:
      LayoutPattern layoutPattern2;
      return layoutPattern2;
label_57:
      layoutPattern2 = layoutPattern1;
      num7 = 1228334403;
      goto label_55;
label_58:
      num7 = 1577178825;
      goto label_55;
    }

    internal void ApplyTo(ZoomWindow window)
    {
label_1:
      int num1 = 28860070;
      while (true)
      {
        int num2 = 1629894069;
        uint num3;
        WindowLayout windowLayout;
        Rectangle rectangle;
        bool flag1;
        bool flag2;
        bool flag3;
        bool flag4;
        int num4;
        int num5;
        int num6;
        int num7;
        switch ((num3 = (uint) (num1 ^ num2)) % 28U)
        {
          case 0:
            if (!window.IsVisible)
            {
              num4 = 0;
              break;
            }
            num1 = 679076188;
            continue;
          case 1:
            rectangle = this.GetRectangle(window);
            num1 = (int) num3 * 1639027476 ^ 426781175;
            continue;
          case 2:
            if (window.IsVisible)
            {
              num1 = 1099507257;
              continue;
            }
            num5 = 0;
            goto label_18;
          case 3:
            num1 = (int) num3 * 156178539 ^ 1893280277;
            continue;
          case 4:
            int num8 = !flag4 ? -1675681083 : (num8 = -1396337757);
            int num9 = (int) num3 * -304495110;
            num1 = num8 ^ num9;
            continue;
          case 5:
            num6 = (uint) windowLayout.WindowVisibility > 0U ? 1 : 0;
            goto label_29;
          case 6:
            num1 = 382279539;
            continue;
          case 7:
            num7 = windowLayout.WindowVisibility == WindowVisibility.Hide ? 1 : 0;
            goto label_33;
          case 8:
            num1 = (int) num3 * 905883272 ^ -1732986473;
            continue;
          case 9:
            num1 = 1806695127;
            continue;
          case 10:
            if (windowLayout != null)
            {
              num1 = (int) num3 * 745170792 ^ -1454658968;
              continue;
            }
            num6 = 0;
            goto label_29;
          case 11:
            num1 = (int) num3 * 1373949443 ^ -168576431;
            continue;
          case 12:
            num1 = (int) num3 * 1171253255 ^ -967206432;
            continue;
          case 13:
            WindowHelper.Move(window.Handle, rectangle, false);
            num1 = (int) num3 * 418210518 ^ 1136401804;
            continue;
          case 14:
            flag1 = rectangle != Rectangle.Empty;
            num1 = (int) num3 * 999511049 ^ -203940173;
            continue;
          case 15:
            int num10 = !flag3 ? -1782432202 : (num10 = -2108884177);
            int num11 = (int) num3 * 520394931;
            num1 = num10 ^ num11;
            continue;
          case 16:
            window.Close(false, \u003CModule\u003E.\u206A‪‫‬‫⁬‎‭‬⁪‌⁮⁯⁭‫‏‭‭‏⁪‍‫⁯⁮⁬⁭‌​⁭⁬‬‪⁬⁮‎⁫⁯‬‏‬‮<string>(2270592879U));
            num1 = (int) num3 * -637264555 ^ -1801916825;
            continue;
          case 17:
            int num12 = flag2 ? 1360019446 : (num12 = 2075374152);
            int num13 = (int) num3 * 746614859;
            num1 = num12 ^ num13;
            continue;
          case 18:
            goto label_3;
          case 19:
            windowLayout = this.GetWindowLayout(window.ZoomWindowType, false);
            num1 = (int) num3 * 1242010947 ^ -1778998054;
            continue;
          case 20:
            int num14 = !flag1 ? 1397665244 : (num14 = 763591177);
            int num15 = (int) num3 * -1206330711;
            num1 = num14 ^ num15;
            continue;
          case 21:
            num4 = windowLayout.WindowVisibility == WindowVisibility.Close ? 1 : 0;
            break;
          case 22:
            window.Hide();
            num1 = (int) num3 * 348730487 ^ 2139556326;
            continue;
          case 23:
            num1 = (int) num3 * -1859921746 ^ 1578629719;
            continue;
          case 24:
            num5 = windowLayout.WindowVisibility == WindowVisibility.Show ? 1 : 0;
            goto label_18;
          case 25:
            num1 = (int) num3 * -2005152156 ^ 202480594;
            continue;
          case 26:
            goto label_1;
          case 27:
            if (!window.IsVisible)
            {
              num7 = 0;
              goto label_33;
            }
            else
            {
              num1 = (int) num3 * -2000741279 ^ -1370600479;
              continue;
            }
          default:
            goto label_42;
        }
        flag2 = num4 != 0;
        num1 = 1859662988;
        continue;
label_18:
        flag3 = num5 != 0;
        num1 = 1730059182;
        continue;
label_29:
        int num16;
        num1 = num16 = num6 != 0 ? 60586994 : (num16 = 382279539);
        continue;
label_33:
        flag4 = num7 != 0;
        num1 = 714393585;
      }
label_42:
      return;
label_3:;
    }

    internal Rectangle GetRectangle(WindowLayout layout)
    {
label_1:
      int num1 = -1319661284;
      Rectangle rectangle1;
      while (true)
      {
        int num2 = -861273064;
        uint num3;
        bool flag;
        Rectangle rectangle2;
        switch ((num3 = (uint) (num1 ^ num2)) % 20U)
        {
          case 0:
            rectangle2 = Rectangle.Empty;
            num1 = (int) num3 * -450963027 ^ 218797705;
            continue;
          case 2:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(layout.Monitor), layout.Horizontal, layout.Vertical);
            num1 = (int) num3 * -1044611785 ^ 905855160;
            continue;
          case 3:
            num1 = (int) num3 * 1735420446 ^ -1643730577;
            continue;
          case 4:
            rectangle1 = rectangle2;
            num1 = -1683498993;
            continue;
          case 5:
            num1 = (int) num3 * -525135154 ^ -801885246;
            continue;
          case 6:
            num1 = (int) num3 * -189269898 ^ 1194809358;
            continue;
          case 7:
            num1 = (int) num3 * 20043550 ^ 490356414;
            continue;
          case 8:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(this.Engine.Settings.PrimaryScreen), layout.Horizontal, layout.Vertical);
            num1 = (int) num3 * -1125848575 ^ -1921771078;
            continue;
          case 9:
            int num4;
            num1 = num4 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(layout.Monitor, Resources.SecondaryMonitor) ? -715836205 : (num4 = -1788272276);
            continue;
          case 10:
            goto label_1;
          case 11:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(this.Engine.Settings.SecondaryScreen), layout.Horizontal, layout.Vertical);
            num1 = (int) num3 * 319474541 ^ -1868293228;
            continue;
          case 12:
            int num5;
            num1 = num5 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(layout.Monitor, \u003CModule\u003E.\u206B‎‏⁫‎‮‌⁪​‪‏⁯‭⁭⁯⁯‭‍‍‬‬⁭⁬⁪‫⁫⁬⁭⁮‌⁮‎‮⁪‮‪⁬‌‪⁬‮<string>(2831708060U)) ? -71348463 : (num5 = -1058643225);
            continue;
          case 13:
            int num6 = !flag ? -1922841105 : (num6 = -1837465590);
            int num7 = (int) num3 * -1975638894;
            num1 = num6 ^ num7;
            continue;
          case 14:
            num1 = (int) num3 * -703420604 ^ 706357324;
            continue;
          case 15:
            num1 = -1035389670;
            continue;
          case 16:
            rectangle2 = Rectangle.Empty;
            num1 = (int) num3 * -1802436062 ^ -379221569;
            continue;
          case 17:
            num1 = (int) num3 * -1650290317 ^ 662765979;
            continue;
          case 18:
            num1 = (int) num3 * 259347053 ^ -217221742;
            continue;
          case 19:
            flag = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(layout.Monitor, Resources.PrimaryMonitor);
            num1 = (int) num3 * -2046581897 ^ -1752252832;
            continue;
          default:
            goto label_21;
        }
      }
label_21:
      return rectangle1;
    }

    internal Rectangle GetRectangle(ZoomWindow window)
    {
label_1:
      int num1 = -724568123;
      Rectangle rectangle1;
      while (true)
      {
        int num2 = -1516929367;
        uint num3;
        Rectangle rectangle2;
        bool flag;
        switch ((num3 = (uint) (num1 ^ num2)) % 8U)
        {
          case 0:
            num1 = (int) num3 * -2113200646 ^ -1930037545;
            continue;
          case 2:
            goto label_1;
          case 3:
            int num4 = flag ? 937545518 : (num4 = 1095412587);
            int num5 = (int) num3 * -1553917635;
            num1 = num4 ^ num5;
            continue;
          case 4:
            rectangle2 = Rectangle.Empty;
            flag = window != null;
            num1 = (int) num3 * 2023299453 ^ 798891054;
            continue;
          case 5:
            rectangle1 = rectangle2;
            num1 = -1548841584;
            continue;
          case 6:
            rectangle2 = this.GetRectangle(window.ZoomWindowType);
            num1 = (int) num3 * 911349000 ^ -2065090586;
            continue;
          case 7:
            num1 = (int) num3 * 490693737 ^ 1136533683;
            continue;
          default:
            goto label_9;
        }
      }
label_9:
      return rectangle1;
    }

    internal Rectangle GetRectangle(ZoomWindowType zoomWindowType)
    {
label_1:
      int num1 = 1460938690;
      Rectangle rectangle1;
      while (true)
      {
        int num2 = 724146166;
        uint num3;
        WindowLayout windowLayout;
        bool flag1;
        bool flag2;
        Rectangle rectangle2;
        bool flag3;
        bool flag4;
        switch ((num3 = (uint) (num1 ^ num2)) % 29U)
        {
          case 0:
            num1 = (int) num3 * -111634654 ^ -1263399230;
            continue;
          case 1:
            num1 = 450272971;
            continue;
          case 2:
            Engine instance = Engine.Instance;
            flag2 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(windowLayout.Monitor, Resources.PrimaryMonitor);
            num1 = (int) num3 * 1124606916 ^ -396775593;
            continue;
          case 4:
            flag3 = windowLayout != null;
            num1 = (int) num3 * -1527788583 ^ 1538787470;
            continue;
          case 5:
            num1 = (int) num3 * -1893581989 ^ -915601666;
            continue;
          case 6:
            num1 = (int) num3 * 1374167926 ^ 155812965;
            continue;
          case 7:
            int num4 = flag1 ? -732322625 : (num4 = -1726203250);
            int num5 = (int) num3 * 938007745;
            num1 = num4 ^ num5;
            continue;
          case 8:
            rectangle1 = rectangle2;
            num1 = 117283663;
            continue;
          case 9:
            rectangle2 = Rectangle.Empty;
            num1 = (int) num3 * -1999204933 ^ 1075303664;
            continue;
          case 10:
            num1 = (int) num3 * 327020002 ^ 1917296878;
            continue;
          case 11:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(this.Engine.Settings.PrimaryScreen), windowLayout.Horizontal, windowLayout.Vertical);
            num1 = (int) num3 * -529916929 ^ -1212964696;
            continue;
          case 12:
            num1 = (int) num3 * -1764257889 ^ 1350180644;
            continue;
          case 13:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(windowLayout.Monitor), windowLayout.Horizontal, windowLayout.Vertical);
            num1 = 1607485356;
            continue;
          case 14:
            rectangle2 = WindowHelper.GetScreenPlacement(LayoutPattern.GetScreen(this.Engine.Settings.SecondaryScreen), windowLayout.Horizontal, windowLayout.Vertical);
            num1 = (int) num3 * 1066209930 ^ 1828242591;
            continue;
          case 15:
            num1 = (int) num3 * -2039157681 ^ 661531970;
            continue;
          case 16:
            rectangle2 = Rectangle.Empty;
            windowLayout = this.GetWindowLayout(zoomWindowType, false);
            num1 = (int) num3 * 1439233639 ^ 426416959;
            continue;
          case 17:
            num1 = (int) num3 * -427622987 ^ 980223762;
            continue;
          case 18:
            int num6;
            num1 = num6 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(windowLayout.Monitor, Resources.SecondaryMonitor) ? 123340918 : (num6 = 2140335020);
            continue;
          case 19:
            int num7 = flag3 ? -754808417 : (num7 = -645617716);
            int num8 = (int) num3 * 589259617;
            num1 = num7 ^ num8;
            continue;
          case 20:
            num1 = (int) num3 * 2090001056 ^ 35471568;
            continue;
          case 21:
            flag4 = !windowLayout.Hidden;
            num1 = (int) num3 * 1867804909 ^ 752663461;
            continue;
          case 22:
            num1 = (int) num3 * 1178927947 ^ 464448750;
            continue;
          case 23:
            int num9 = !flag4 ? 275628100 : (num9 = 1002413232);
            int num10 = (int) num3 * -466574293;
            num1 = num9 ^ num10;
            continue;
          case 24:
            goto label_1;
          case 25:
            flag1 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(windowLayout.Monitor, \u003CModule\u003E.\u202A⁭⁪⁮‎⁬‪‫⁯‪‪‏‮‬⁫‎‏‌⁪‌⁬‫‬⁮‌‍⁬⁫‫‌⁮‌‌‮⁬⁬⁮‫‪‮‮<string>(1218923328U));
            num1 = 1424153758;
            continue;
          case 26:
            num1 = 1051788833;
            continue;
          case 27:
            num1 = 1423742680;
            continue;
          case 28:
            int num11 = !flag2 ? 1284933294 : (num11 = 241891092);
            int num12 = (int) num3 * -1373891181;
            num1 = num11 ^ num12;
            continue;
          default:
            goto label_30;
        }
      }
label_30:
      return rectangle1;
    }

    public void Save(string filePath = "")
    {
      try
      {
label_2:
        int num1 = -270656283;
        while (true)
        {
          int num2 = -1496834357;
          uint num3;
          bool flag;
          switch ((num3 = (uint) (num1 ^ num2)) % 9U)
          {
            case 0:
              filePath = LayoutPattern.\u202C⁬‬‭‍⁯⁭‌‫⁭⁬‮‎⁭‪​‫⁪‬‪‬‫⁬⁯⁯‫⁬⁮⁪‬‍‬‎⁫‭‎‌‎‭‫‮(this.Engine.Settings.LayoutsRoot, LayoutPattern.\u202D‮⁫⁯⁬‏‌⁭⁬⁮‏⁫‭⁪‏⁫‭‌​‏‫⁪‫‪‮‪​​‭‪‍‮‏‬‭‌‌⁯⁬‫‮(this.PatternName, \u003CModule\u003E.\u200E‏⁯‍‬⁭⁪‌‌‌⁪⁫‫‎⁫‮⁬‎‌⁮⁪⁪⁭‍‌⁫‮‬‎⁬‎‌‎‌⁪‫‬‮⁮‮<string>(3744688220U)));
              num1 = (int) num3 * 392040777 ^ -1874492919;
              continue;
            case 1:
              flag = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(filePath, string.Empty);
              num1 = (int) num3 * -804475847 ^ -509500767;
              continue;
            case 2:
              if (!this.AutoGenerated)
              {
                num1 = (int) num3 * 1458024292 ^ -1755768071;
                continue;
              }
              goto label_26;
            case 3:
              int num4 = flag ? -698646940 : (num4 = -1623560109);
              int num5 = (int) num3 * -620874660;
              num1 = num4 ^ num5;
              continue;
            case 4:
              num1 = (int) num3 * 1186689813 ^ -1950535044;
              continue;
            case 6:
              num1 = (int) num3 * -1632268354 ^ -365905545;
              continue;
            case 7:
              CoreUtils.DeleteFile(filePath);
              num1 = -590132038;
              continue;
            case 8:
              goto label_2;
            default:
              goto label_12;
          }
        }
label_12:
        // ISSUE: type reference
        XmlSerializer xmlSerializer = LayoutPattern.\u202D⁭‮‎‍⁮⁪‏‎‪⁭‏⁭​‍‎‫‪‮‮⁬‬⁭‬‏​‌‫⁯‌⁮‮‬⁮‪⁫‫‏‫‌‮(LayoutPattern.\u202A‎‎‌‬‏‭⁭‍⁯‎⁭‬⁬‎‮‬‍⁭‭‭⁬⁪‬​⁭‎‏‪‎‮‫‍​‭‮‫‭‮⁮‮(__typeref (LayoutPattern)));
        TextWriter textWriter = (TextWriter) LayoutPattern.\u200C‍‬⁫‎⁯⁬⁭⁯⁪⁯‭‍‌‎⁪⁮‏‌‎‍‍⁬‏‮⁫‎‍‍⁪‭‮‎‪‎‌‮‏⁮‭‮(filePath);
        try
        {
          LayoutPattern.\u200F⁭‌⁮‌⁮⁪‎‎‏‬‌‭‬⁮⁮‏‫‎​‬‍‎‫⁯‮⁯‏‌‎‬‮‪​‮‍⁬⁯⁪‮(xmlSerializer, textWriter, (object) this);
          LayoutPattern.\u206F‎‭‬‌⁫‌⁬‍⁫‭‭‪‌⁭⁫⁮⁮‮​​‏‭‭‮‎‍‮‏⁫‫⁬⁬‫⁪‮‬⁫‫‫‮(textWriter);
label_14:
          int num2 = -1468175596;
          while (true)
          {
            int num3 = -1496834357;
            uint num4;
            switch ((num4 = (uint) (num2 ^ num3)) % 3U)
            {
              case 0:
                goto label_14;
              case 1:
                num2 = (int) num4 * -674079871 ^ 1411389559;
                continue;
              default:
                goto label_22;
            }
          }
        }
        finally
        {
          if (textWriter != null)
          {
label_18:
            int num2 = -104426927;
            while (true)
            {
              int num3 = -1496834357;
              uint num4;
              switch ((num4 = (uint) (num2 ^ num3)) % 3U)
              {
                case 1:
                  LayoutPattern.\u200F‪⁯⁫‬‎⁯‭‮‬⁬⁯‬‍‍‏‫⁭‬​‮‏‮‫‮‬⁭⁯‬⁬⁯‭​‮⁪‏‎⁬⁭⁭‮((IDisposable) textWriter);
                  num2 = (int) num4 * 900409025 ^ 1019844015;
                  continue;
                case 2:
                  goto label_18;
                default:
                  goto label_21;
              }
            }
          }
label_21:;
        }
label_22:
        // ISSUE: type reference
        ((CompositePresentationEvent<ObjectChangedEventPayload>) this._eventAggregator.GetEvent<ObjectChangeEvent>()).Publish(new ObjectChangedEventPayload()
        {
          ChangeType = ChangeType.Saved,
          ObjectType = LayoutPattern.\u202A‎‎‌‬‏‭⁭‍⁯‎⁭‬⁬‎‮‬‍⁭‭‭⁬⁪‬​⁭‎‏‪‎‮‫‍​‭‮‫‭‮⁮‮(__typeref (LayoutPattern)),
          ChangedObject = (object) this
        });
label_23:
        int num6 = -209392826;
label_24:
        while (true)
        {
          int num2 = -1496834357;
          uint num3;
          switch ((num3 = (uint) (num6 ^ num2)) % 4U)
          {
            case 0:
              goto label_36;
            case 1:
              goto label_26;
            case 2:
              num6 = (int) num3 * 212697712 ^ 145059811;
              continue;
            case 3:
              goto label_23;
            default:
              goto label_32;
          }
        }
label_32:
        return;
label_36:
        return;
label_26:
        this.IsDirty = false;
        num6 = -1412035511;
        goto label_24;
      }
      catch (Exception ex)
      {
label_30:
        int num1 = -1985995499;
        while (true)
        {
          int num2 = -1496834357;
          uint num3;
          switch ((num3 = (uint) (num1 ^ num2)) % 5U)
          {
            case 0:
              num1 = (int) num3 * -733491898 ^ 828565919;
              continue;
            case 1:
              num1 = (int) num3 * 35608506 ^ 2062486697;
              continue;
            case 2:
              goto label_30;
            case 3:
              goto label_28;
            case 4:
              LayoutPattern.\u202C‭‬‮⁮⁫‫‮‫‪‪⁫‏‍⁫‫‭⁫‍⁫⁮⁫‫⁭‌‮⁭‏‌⁭‍‍⁬‪‫⁪​‬⁪⁫‮(CoreObject.log, (object) ex);
              num1 = (int) num3 * -324944419 ^ 70092789;
              continue;
            default:
              goto label_25;
          }
        }
label_25:
        return;
label_28:;
      }
    }

    internal static Screen GetScreen(string name)
    {
label_1:
      int num1 = 1957525996;
      Screen screen1;
      while (true)
      {
        int num2 = 481900695;
        uint num3;
        Screen[] screenArray;
        string str;
        int index;
        Screen screen2;
        bool flag1;
        bool flag2;
        switch ((num3 = (uint) (num1 ^ num2)) % 32U)
        {
          case 0:
            int num4;
            num1 = num4 = index >= screenArray.Length ? 1796334010 : (num4 = 1916894168);
            continue;
          case 1:
            num1 = (int) num3 * 2051609349 ^ 1963626812;
            continue;
          case 2:
            num1 = 37809217;
            continue;
          case 3:
            num1 = (int) num3 * 510377376 ^ -121473405;
            continue;
          case 4:
            num1 = (int) num3 * -1941470824 ^ -509723178;
            continue;
          case 5:
            num1 = (int) num3 * 1730696221 ^ 1936091025;
            continue;
          case 6:
            num1 = (int) num3 * -1183252254 ^ -387487576;
            continue;
          case 7:
            str = ZoomZoom.Properties.Settings.Default._App_PrimaryMonitor;
            num1 = (int) num3 * -1132311363 ^ 431237495;
            continue;
          case 8:
            int num5 = flag1 ? 1807489638 : (num5 = 85038421);
            int num6 = (int) num3 * -1037104972;
            num1 = num5 ^ num6;
            continue;
          case 9:
            num1 = (int) num3 * 709542532 ^ -1148833792;
            continue;
          case 10:
            goto label_1;
          case 11:
            num1 = (int) num3 * 1553879719 ^ 1620383430;
            continue;
          case 12:
            flag2 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(str, string.Empty);
            num1 = 2032461198;
            continue;
          case 13:
            screen1 = LayoutPattern.\u202B⁭⁭‍‏⁭‭‭⁬⁭‌‎⁭​‬⁭‎​⁯‭⁯⁭⁭‪‮‌⁭⁫‌​‏‪‪⁪⁪‪‮‭⁪‪‮();
            num1 = (int) num3 * -1988936939 ^ 144595919;
            continue;
          case 14:
            screenArray = LayoutPattern.\u200F‭‏⁮‪‏⁭‭‏‮⁭‪‭‍⁭⁭‪​‪‪⁬‬‍‮‎‭‪​‫‫​⁭‏⁮⁬‍⁮‭⁬‮();
            num1 = 144987213;
            continue;
          case 15:
            screen2 = screenArray[index];
            num1 = 1255407956;
            continue;
          case 16:
            str = ZoomZoom.Properties.Settings.Default._App_SecondaryMonitor;
            num1 = (int) num3 * -1898353106 ^ 810041075;
            continue;
          case 17:
            num1 = (int) num3 * 2079407896 ^ -1862011856;
            continue;
          case 18:
            num1 = (int) num3 * -589427041 ^ -1047199383;
            continue;
          case 20:
            flag1 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(LayoutPattern.\u202E‪‭‭‭⁭‎⁪‏‏⁯⁮⁬‎‏⁪‬‫‬⁪⁪‎‭⁫‍⁮‭⁫⁬⁭⁫​‪‫‌‮‌⁯‮‍‮(screen2), str);
            num1 = (int) num3 * -1701353319 ^ 1206692203;
            continue;
          case 21:
            num1 = (int) num3 * 883060771 ^ 291394703;
            continue;
          case 22:
            ++index;
            num1 = (int) num3 * -1712204801 ^ 404049309;
            continue;
          case 23:
            screen1 = LayoutPattern.\u202B⁭⁭‍‏⁭‭‭⁬⁭‌‎⁭​‬⁭‎​⁯‭⁯⁭⁭‪‮‌⁭⁫‌​‏‪‪⁪⁪‪‮‭⁪‪‮();
            num1 = (int) num3 * 1856835010 ^ -1482852321;
            continue;
          case 24:
            int num7 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(str, Resources.PrimaryMonitor) ? -1456680638 : (num7 = -1933150998);
            int num8 = (int) num3 * 1160436516;
            num1 = num7 ^ num8;
            continue;
          case 25:
            int num9 = !flag2 ? 869644198 : (num9 = 1852713293);
            int num10 = (int) num3 * -2007232745;
            num1 = num9 ^ num10;
            continue;
          case 26:
            index = 0;
            num1 = (int) num3 * 2019933961 ^ -1508658909;
            continue;
          case 27:
            str = name;
            num1 = (int) num3 * 891428894 ^ -1815348251;
            continue;
          case 28:
            num1 = (int) num3 * -1164157428 ^ -1142512183;
            continue;
          case 29:
            int num11;
            num1 = num11 = LayoutPattern.\u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮(str, Resources.SecondaryMonitor) ? 881379845 : (num11 = 265399963);
            continue;
          case 30:
            num1 = (int) num3 * -826938958 ^ -865702805;
            continue;
          case 31:
            screen1 = screen2;
            num1 = (int) num3 * -1349671960 ^ -1552774084;
            continue;
          default:
            goto label_33;
        }
      }
label_33:
      return screen1;
    }

    internal WindowLayout GetWindowLayout(ZoomWindowType zoomWindowType, bool createWhenMissing)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      LayoutPattern.\u003C\u003Ec__DisplayClass50_0 cDisplayClass500 = new LayoutPattern.\u003C\u003Ec__DisplayClass50_0();
      // ISSUE: reference to a compiler-generated field
      cDisplayClass500.zoomWindowType = zoomWindowType;
label_1:
      int num1 = -1032494097;
      WindowLayout windowLayout1;
      while (true)
      {
        int num2 = -485247388;
        uint num3;
        WindowLayout windowLayout2;
        bool flag;
        int num4;
        switch ((num3 = (uint) (num1 ^ num2)) % 11U)
        {
          case 0:
            windowLayout1 = windowLayout2;
            num1 = -527404386;
            continue;
          case 1:
            // ISSUE: reference to a compiler-generated field
            windowLayout2 = this.AddWindowLayout(cDisplayClass500.zoomWindowType, WindowVisibility.Ignore);
            num1 = (int) num3 * 917721855 ^ -1345026909;
            continue;
          case 2:
            num1 = (int) num3 * -503645621 ^ 1838770583;
            continue;
          case 3:
            if (windowLayout2 == null)
            {
              num4 = 0;
              break;
            }
            num1 = -557592933;
            continue;
          case 4:
            int num5 = flag ? 1361352317 : (num5 = 1083422831);
            int num6 = (int) num3 * 501730135;
            num1 = num5 ^ num6;
            continue;
          case 5:
            num1 = (int) num3 * 1617451557 ^ 682411181;
            continue;
          case 6:
            windowLayout2.SetPattern(this);
            num1 = (int) num3 * -865123966 ^ -1275791738;
            continue;
          case 7:
            goto label_1;
          case 9:
            num4 = windowLayout2.Pattern == null ? 1 : 0;
            break;
          case 10:
            // ISSUE: method pointer
            windowLayout2 = (WindowLayout) Enumerable.FirstOrDefault<WindowLayout>((IEnumerable<M0>) this.WindowLayouts, (Func<M0, bool>) new Func<WindowLayout, bool>((object) cDisplayClass500, __methodptr(\u003CGetWindowLayout\u003Eb__0)));
            int num7 = windowLayout2 == null & createWhenMissing ? -1977497861 : (num7 = -361823332);
            int num8 = (int) num3 * 2020090825;
            num1 = num7 ^ num8;
            continue;
          default:
            goto label_15;
        }
        flag = num4 != 0;
        num1 = -1469405243;
      }
label_15:
      return windowLayout1;
    }

    static bool \u200B‫‌⁭⁮⁪‍‪‏‍‬‫⁯‫⁫⁬‪‏‫‪⁬⁮‮‏‍‮‪‍‎⁪​‍⁮‎⁫‬⁮⁪‍⁫‮([In] string obj0, [In] string obj1)
    {
      return obj0.Equals(obj1);
    }

    static string \u200E‪‪⁫‏⁫‭‫⁮⁯‏‬‎‌‍‭⁯‎‎⁭‎⁭‌‬‫‬‌‌‬‍‮⁮⁮‫⁭⁭‌‍‎‭‮([In] string obj0, [In] string obj1, [In] string obj2)
    {
      return obj0.Replace(obj1, obj2);
    }

    static string \u206D‎​‪‏‭‫⁮‭⁪⁪‫‫⁭‪‎‎‌⁪‏⁯‍‪⁬‌‏​‬‫‮⁮​⁭⁭‬‍‭⁪‫⁫‮([In] string obj0, [In] object obj1, [In] object obj2)
    {
      return string.Format(obj0, obj1, obj2);
    }

    static string \u202D‮⁫⁯⁬‏‌⁭⁬⁮‏⁫‭⁪‏⁫‭‌​‏‫⁪‫‪‮‪​​‭‪‍‮‏‬‭‌‌⁯⁬‫‮([In] string obj0, [In] string obj1)
    {
      return obj0 + obj1;
    }

    static bool \u206F‬‍‭‬⁬⁮⁪⁯⁬‌‫‫‮‭⁭⁬⁫‭‌⁮⁯⁪⁫‍‮‎‬⁭⁪‌‌‪⁫⁭⁭‭‎‫‬‮([In] IEnumerator obj0)
    {
      return obj0.MoveNext();
    }

    static void \u200F‪⁯⁫‬‎⁯‭‮‬⁬⁯‬‍‍‏‫⁭‬​‮‏‮‫‮‬⁭⁯‬⁬⁯‭​‮⁪‏‎⁬⁭⁭‮([In] IDisposable obj0)
    {
      obj0.Dispose();
    }

    static void \u200D‍‍⁮‮‪⁬‬‬‎⁮⁮‏‌‍‬​⁫⁫⁪‫⁯‭⁭‍⁪‌‌‮​⁭‏‮⁬‍‌⁮‫⁯‫‮([In] string obj0)
    {
      File.Delete(obj0);
    }

    static void \u202C‭‬‮⁮⁫‫‮‫‪‪⁫‏‍⁫‫‭⁫‍⁫⁮⁫‫⁭‌‮⁭‏‌⁭‍‍⁬‪‫⁪​‬⁪⁫‮([In] ILog obj0, [In] object obj1)
    {
      obj0.Error(obj1);
    }

    bool \u202B⁪⁯⁪⁮‮‮⁮‍⁭‮‍⁬⁬‎‬‮⁮⁮⁮⁪⁫‪‍⁪⁯‬​⁪⁬‎⁪‪‍⁪⁯⁭‫‪‬‮([In] object obj0)
    {
      return base.Equals(obj0);
    }

    static bool \u200E‮‮‫⁫‌‮⁬​‬​​‫‌⁪‭​⁭‫⁯‎‪‍‪‎‎⁫⁮⁪‮‏​‍⁯⁯‎​‌⁫‮([In] string obj0)
    {
      return string.IsNullOrEmpty(obj0);
    }

    static int \u206B‎⁫⁭⁬‍‭⁪⁯⁪‌⁫‍‫⁪⁯⁮‍​‪‬‪‍‫‬⁯‏‫⁮⁮​⁭⁬‍‌⁪⁬‎⁮‎‮([In] object obj0)
    {
      return obj0.GetHashCode();
    }

    int \u206F‫⁪‭​‎‫‫‏⁬‌⁯‪⁪‫‭‭‏‭⁬‍⁬⁬‍‍​⁫‏‫⁭‪‮​⁫‫‍‍​‎‎‮()
    {
      return base.GetHashCode();
    }

    static bool \u202A‬‎⁯‬​⁬‎⁭‎⁮‌⁬‫⁫‌‬‮‍‌⁭‭⁭⁪⁪‪​‎‪⁯‫⁭‪‮‏‍‍‪⁭⁯‮([In] string obj0)
    {
      return File.Exists(obj0);
    }

    static System.Type \u202A‎‎‌‬‏‭⁭‍⁯‎⁭‬⁬‎‮‬‍⁭‭‭⁬⁪‬​⁭‎‏‪‎‮‫‍​‭‮‫‭‮⁮‮([In] RuntimeTypeHandle obj0)
    {
      return System.Type.GetTypeFromHandle(obj0);
    }

    static XmlSerializer \u202D⁭‮‎‍⁮⁪‏‎‪⁭‏⁭​‍‎‫‪‮‮⁬‬⁭‬‏​‌‫⁯‌⁮‮‬⁮‪⁫‫‏‫‌‮([In] System.Type obj0)
    {
      return new XmlSerializer(obj0);
    }

    static StreamReader \u202A‫‫‬‌‍‫‍‬⁮‌⁭‎⁯‍‍‭‌⁪‭‫‌‎‎⁭‎‪‌‏⁮‎‮⁯⁬⁭‭‍‌‍⁬‮([In] string obj0)
    {
      return new StreamReader(obj0);
    }

    static object \u202E​⁯⁮‎‌‮‌‬‬‎⁬‍‏⁪⁭⁯⁯⁬‎⁯‍‪⁪⁫‪‌​‭​‮⁭‫⁯⁭⁭⁮⁪‪‫‮([In] XmlSerializer obj0, [In] TextReader obj1)
    {
      return obj0.Deserialize(obj1);
    }

    static void \u206A‎‭‫‮‫​‫‫‍​‍​⁬⁭⁯⁭⁬‭⁫‫⁬⁫⁯‬‍‭‮⁯‌⁭‫⁬‍⁯⁪⁯⁪‬⁮‮([In] TextReader obj0)
    {
      obj0.Close();
    }

    static string \u202C⁬‬‭‍⁯⁭‌‫⁭⁬‮‎⁭‪​‫⁪‬‪‬‫⁬⁯⁯‫⁬⁮⁪‬‍‬‎⁫‭‎‌‎‭‫‮([In] string obj0, [In] string obj1)
    {
      return Path.Combine(obj0, obj1);
    }

    static StreamWriter \u200C‍‬⁫‎⁯⁬⁭⁯⁪⁯‭‍‌‎⁪⁮‏‌‎‍‍⁬‏‮⁫‎‍‍⁪‭‮‎‪‎‌‮‏⁮‭‮([In] string obj0)
    {
      return new StreamWriter(obj0);
    }

    static void \u200F⁭‌⁮‌⁮⁪‎‎‏‬‌‭‬⁮⁮‏‫‎​‬‍‎‫⁯‮⁯‏‌‎‬‮‪​‮‍⁬⁯⁪‮([In] XmlSerializer obj0, [In] TextWriter obj1, [In] object obj2)
    {
      obj0.Serialize(obj1, obj2);
    }

    static void \u206F‎‭‬‌⁫‌⁬‍⁫‭‭‪‌⁭⁫⁮⁮‮​​‏‭‭‮‎‍‮‏⁫‫⁬⁬‫⁪‮‬⁫‫‫‮([In] TextWriter obj0)
    {
      obj0.Close();
    }

    static Screen \u202B⁭⁭‍‏⁭‭‭⁬⁭‌‎⁭​‬⁭‎​⁯‭⁯⁭⁭‪‮‌⁭⁫‌​‏‪‪⁪⁪‪‮‭⁪‪‮()
    {
      return Screen.PrimaryScreen;
    }

    static Screen[] \u200F‭‏⁮‪‏⁭‭‏‮⁭‪‭‍⁭⁭‪​‪‪⁬‬‍‮‎‭‪​‫‫​⁭‏⁮⁬‍⁮‭⁬‮()
    {
      return Screen.AllScreens;
    }

    static string \u202E‪‭‭‭⁭‎⁪‏‏⁯⁮⁬‎‏⁪‬‫‬⁪⁪‎‭⁫‍⁮‭⁫⁬⁭⁫​‪‫‌‮‌⁯‮‍‮([In] Screen obj0)
    {
      return obj0.DeviceName;
    }
  }
}
